if(NOT PROTOBUF_LIBPPROTOBUF_NAME)
	message(FATAL_ERROR "PROTOBUF_LIBPPROTOBUF_NAME is empty")
endif()

set_target_properties(${PROTOBUF_LIBPPROTOBUF_NAME} PROPERTIES
	CXX_STANDARD 11
	CXX_STANDARD_REQUIRED ON
	CXX_EXTENSIONS OFF
)

if(WINDOWS)
	set_target_properties(${PROTOBUF_LIBPPROTOBUF_NAME} PROPERTIES MSVC_RUNTIME_LIBRARY "MultiThreaded$<$<CONFIG:Debug>:Debug>")
endif()

target_compile_options(${PROTOBUF_LIBPPROTOBUF_NAME} PRIVATE ${PLATFORM_COMPILER_OPTIONS})
target_link_options(${PROTOBUF_LIBPPROTOBUF_NAME} PRIVATE ${PLATFORM_LINK_OPTIONS})

target_compile_definitions(${PROTOBUF_LIBPPROTOBUF_NAME} PRIVATE ${PLATFORM_COMPILE_DEFINITIONS})
target_include_directories(${PROTOBUF_LIBPPROTOBUF_NAME} PRIVATE ${PLATFORM_INCLUDE_DIRS})
