if(NOT PROTOBUF_PROTOC_NAME)
	message(FATAL_ERROR "PROTOBUF_PROTOC_NAME is empty")
endif()

set_target_properties(${PROTOBUF_PROTOC_NAME} PROPERTIES
	CXX_STANDARD 11
	CXX_STANDARD_REQUIRED ON
	CXX_EXTENSIONS OFF
)

if(WIN32)
	set_target_properties(${PROTOBUF_PROTOC_NAME} PROPERTIES MSVC_RUNTIME_LIBRARY "MultiThreaded$<$<CONFIG:Debug>:Debug>")
endif()

target_compile_options(${PROTOBUF_PROTOC_NAME} PRIVATE ${PLATFORM_COMPILER_OPTIONS})
target_link_options(${PROTOBUF_PROTOC_NAME} PRIVATE ${PLATFORM_LINKER_OPTIONS})

target_compile_definitions(${PROTOBUF_PROTOC_NAME} PRIVATE ${PLATFORM_COMPILE_DEFINITIONS})
target_include_directories(${PROTOBUF_PROTOC_NAME} PRIVATE ${PLATFORM_INCLUDE_DIR})
