//======= Copyright © 2005, , Valve Corporation, All rights reserved. =========
//
// Purpose: Variant Pearson Hash general purpose hashing algorithm described
//			by Cargill in C++ Report 1994.  Generates a 16-bit result.
//
//=============================================================================

#include <stdlib.h>
#include "tier0/basetypes.h"
#include "tier0/dbg.h"
#include "tier0/platform.h"
#include "tier0/strtools.h"
#include "generichash.h"

// NOTE: This has to be the last file included!
#include "tier0/memdbgon.h"

//-----------------------------------------------------------------------------
//
// Table of randomly shuffled values from 0-255 generated by:
//
//-----------------------------------------------------------------------------
/*
void MakeRandomValues()
{
	int i, j, r;
	unsigned  t;
	srand( 0xdeadbeef );

	for ( i = 0; i < 256; i++ )
	{
		g_nRandomValues[i] = (unsigned )i;
	}

	for (j = 0; j < 8; j++)
	{
		for (i = 0; i < 256; i++)
		{
			r = rand() & 0xff;
			t = g_nRandomValues[i];
			g_nRandomValues[i] = g_nRandomValues[r];
			g_nRandomValues[r] = t;
		}
	}

	printf("static unsigned g_nRandomValues[256] =\n{\n");

	for (i = 0; i < 256; i += 16)
	{
		printf("\t");
		for (j = 0; j < 16; j++)
			printf(" %3d,", g_nRandomValues[i+j]);
		printf("\n");
	}
	printf("};\n");
}
*/

// The table itself lives in GenericHash::detail::kRandVals, see generichash.h.

//-----------------------------------------------------------------------------
// String 
//-----------------------------------------------------------------------------
unsigned FASTCALL HashString( const char *pszKey )
{
	return MurmurHash2( pszKey, (uint32)V_strlen( pszKey ), 0x3501A674 );
}


//-----------------------------------------------------------------------------
// Case-insensitive string 
//-----------------------------------------------------------------------------
unsigned FASTCALL HashStringCaseless( const char *pszKey )
{
	return MurmurHash2LowerCase( pszKey, 0x3501A674 );
}

//-----------------------------------------------------------------------------
// 32 bit conventional case-insensitive string 
//-----------------------------------------------------------------------------
unsigned FASTCALL HashStringFastCaselessConventional( const char *pszKey )
{
	uint32 hash = 0xAAAAAAAA; // Alternating 1's and 0's to maximize the effect of the later multiply and add
	hash += ( 2 * (uint32)V_strlen( pszKey ) ); // Add the string length * 2 to the hash to give it more variety

	for( ; *pszKey ; pszKey++ )
	{
		hash = ( ( hash << 5 ) + hash ) + (uint8)TOLOWERU(*pszKey);
	}

	return hash;
}

//-----------------------------------------------------------------------------
// 4-byte hash
//-----------------------------------------------------------------------------
unsigned FASTCALL Hash4( const void *pKey )
{
	const uint32 *	p = (const uint32 *) pKey;
	unsigned		even,
							odd,
							n;
	n     = *p;
	odd   = GenericHash::detail::kRandVals[((n >> 8) & 0xff)];
	even  = GenericHash::detail::kRandVals[odd ^ (n >> 24)];
	odd   = GenericHash::detail::kRandVals[even ^ (n >> 16) & 0xff];
	even  = GenericHash::detail::kRandVals[odd ^ (n >> 8) & 0xff];
	odd   = GenericHash::detail::kRandVals[even  ^ (n & 0xff)];

	return (even << 8) | odd;
}


//-----------------------------------------------------------------------------
// 8-byte hash
//-----------------------------------------------------------------------------
unsigned FASTCALL Hash8( const void *pKey )
{
	const uint32 *	p = (const uint32 *) pKey;
	unsigned		even,
							odd,
							n;
	n     = *p;
	odd   = GenericHash::detail::kRandVals[((n >> 8) & 0xff)];
	even  = GenericHash::detail::kRandVals[odd ^ (n >> 24)];
	odd   = GenericHash::detail::kRandVals[even ^ (n >> 16) & 0xff];
	even  = GenericHash::detail::kRandVals[odd ^ (n >> 8) &  0xff];
	odd   = GenericHash::detail::kRandVals[even  ^ (n & 0xff)];

	n     = *(p+1);
	even  = GenericHash::detail::kRandVals[odd ^ (n >> 24)];
	odd   = GenericHash::detail::kRandVals[even  ^ (n >> 16) & 0xff];
	even  = GenericHash::detail::kRandVals[odd ^ (n >> 8) & 0xff];
	odd   = GenericHash::detail::kRandVals[even  ^ (n & 0xff)];

	return (even << 8) | odd;
}


//-----------------------------------------------------------------------------
// 12-byte hash
//-----------------------------------------------------------------------------
unsigned FASTCALL Hash12( const void *pKey )
{
	const uint32 *	p = (const uint32 *) pKey;
	unsigned		even,
							odd,
							n;
	n     = *p;
	odd   = GenericHash::detail::kRandVals[((n >> 8) & 0xff)];

	even  = GenericHash::detail::kRandVals[odd ^ (n >> 24)];
	odd   = GenericHash::detail::kRandVals[even ^ (n >> 16) & 0xff];
	even  = GenericHash::detail::kRandVals[odd ^ (n >> 8) &  0xff];
	odd   = GenericHash::detail::kRandVals[even  ^ (n & 0xff)];

	n     = *(p+1);
	even  = GenericHash::detail::kRandVals[odd ^ (n >> 24)];
	odd   = GenericHash::detail::kRandVals[even  ^ (n >> 16) & 0xff];
	even  = GenericHash::detail::kRandVals[odd ^ (n >> 8) &  0xff];
	odd   = GenericHash::detail::kRandVals[even  ^ (n & 0xff)];

	n     = *(p+2);
	even  = GenericHash::detail::kRandVals[odd ^ (n >> 24)];
	odd   = GenericHash::detail::kRandVals[even  ^ (n >> 16) & 0xff];
	even  = GenericHash::detail::kRandVals[odd ^ (n >> 8) &  0xff];
	odd   = GenericHash::detail::kRandVals[even  ^ (n & 0xff)];

	return (even << 8) | odd;
}


//-----------------------------------------------------------------------------
// 16-byte hash
//-----------------------------------------------------------------------------
unsigned FASTCALL Hash16( const void *pKey )
{
	const uint32 *	p = (const uint32 *) pKey;
	unsigned		even,
							odd,
							n;
	n     = *p;
	odd   = GenericHash::detail::kRandVals[((n >> 8) & 0xff)];

	even  = GenericHash::detail::kRandVals[odd ^ (n >> 24)];
	odd   = GenericHash::detail::kRandVals[even ^ (n >> 16) & 0xff];
	even  = GenericHash::detail::kRandVals[odd ^ (n >> 8) &  0xff];
	odd   = GenericHash::detail::kRandVals[even  ^ (n & 0xff)];

	n     = *(p+1);
	even  = GenericHash::detail::kRandVals[odd ^ (n >> 24)];
	odd   = GenericHash::detail::kRandVals[even  ^ (n >> 16) & 0xff];
	even  = GenericHash::detail::kRandVals[odd ^ (n >> 8) & 0xff];
	odd   = GenericHash::detail::kRandVals[even  ^ (n & 0xff)];

	n     = *(p+2);
	even  = GenericHash::detail::kRandVals[odd ^ (n >> 24)];
	odd   = GenericHash::detail::kRandVals[even  ^ (n >> 16) & 0xff];
	even  = GenericHash::detail::kRandVals[odd ^ (n >> 8) &  0xff];
	odd   = GenericHash::detail::kRandVals[even  ^ (n & 0xff)];

	n     = *(p+3);
	even  = GenericHash::detail::kRandVals[odd ^ (n >> 24)];
	odd   = GenericHash::detail::kRandVals[even  ^ (n >> 16) & 0xff];
	even  = GenericHash::detail::kRandVals[odd ^ (n >> 8) &  0xff];
	odd   = GenericHash::detail::kRandVals[even  ^ (n & 0xff)];

	return (even << 8) | odd;
}


//-----------------------------------------------------------------------------
// Arbitrary fixed length hash
//-----------------------------------------------------------------------------
unsigned FASTCALL HashBlock( const void *pKey, unsigned size )
{
	const uint8 *	k    = (const uint8 *) pKey;
	unsigned 		even = 0,
					odd  = 0,
					n;

	while (size)
	{
		--size;
		n    = *k++;
		even = GenericHash::detail::kRandVals[odd ^ n];
		if (size)
		{
			--size;
			n   = *k++;
			odd = GenericHash::detail::kRandVals[even ^ n];
		}
		else
			break;
	}

	return (even << 8) | odd;
}


//-----------------------------------------------------------------------------
// Murmur hash
//-----------------------------------------------------------------------------
uint32 MurmurHash2( const void * key, int len, uint32 seed )
{
	// They're not really 'magic', they just happen to work well.

	const uint32 m = 0x5bd1e995;
	const int r = 24;

	// Initialize the hash to a 'random' value

	uint32 h = seed ^ len;

	// Mix 4 bytes at a time into the hash

	const unsigned char * data = (const unsigned char *)key;

	while(len >= 4)
	{
		uint32 k = LittleDWord( *(uint32 *)data );

		k *= m; 
		k ^= k >> r; 
		k *= m; 

		h *= m; 
		h ^= k;

		data += 4;
		len -= 4;
	}

	// Handle the last few bytes of the input array

	switch(len)
	{
	case 3: h ^= data[2] << 16;
	case 2: h ^= data[1] << 8;
	case 1: h ^= data[0];
		h *= m;
	};

	// Do a few final mixes of the hash to ensure the last few
	// bytes are well-incorporated.

	h ^= h >> 13;
	h *= m;
	h ^= h >> 15;

	return h;
}

uint32 MurmurHash2LowerCase( char const *pString, int len, uint32 nSeed )
{
	char *p = ( char * ) stackalloc( len + 1 );
	for( int i = 0; i < len ; i++ )
	{
		p[i] = TOLOWERU( pString[i] );
	}
	return MurmurHash2(p, len, nSeed ); 
}

//-----------------------------------------------------------------------------
// Murmur hash, 64 bit- endian neutral
//-----------------------------------------------------------------------------
uint64 MurmurHash64( const void * key, int len, uint32 seed )
{
	// 'm' and 'r' are mixing constants generated offline.
	// They're not really 'magic', they just happen to work well.

	const uint32 m = 0x5bd1e995;
	const int r = 24;

	// Initialize the hash to a 'random' value

	uint32 h1 = seed ^ len;
	uint32 h2 = 0;

	// Mix 4 bytes at a time into the hash

	const uint32 * data = (const uint32 *)key;
	while ( len >= 8 )
	{
		uint32 k1 = LittleDWord( *data++ );
		k1 *= m; k1 ^= k1 >> r; k1 *= m;
		h1 *= m; h1 ^= k1;
		len -= 4;

		uint32 k2 = LittleDWord( *data++ );
		k2 *= m; k2 ^= k2 >> r; k2 *= m;
		h2 *= m; h2 ^= k2;
		len -= 4;
	}

	if(len >= 4)
	{
		uint32 k1 = LittleDWord( *data++ );
		k1 *= m; k1 ^= k1 >> r; k1 *= m;
		h1 *= m; h1 ^= k1;
		len -= 4;
	}

	// Handle the last few bytes of the input array
	switch(len)
	{
	case 3: h2 ^= ((uint8*)data)[2] << 16;
	case 2: h2 ^= ((uint8*)data)[1] << 8;
	case 1: h2 ^= ((uint8*)data)[0];
			h2 *= m;
	};

	h1 ^= h2 >> 18; h1 *= m;
	h2 ^= h1 >> 22; h2 *= m;
	h1 ^= h2 >> 17; h1 *= m;
	h2 ^= h1 >> 19; h2 *= m;

	uint64 h = h1;

	h = (h << 32) | h2;

	return h;
}
