#include "codegen.h"
#include "script.h"

#include <cstdarg>

namespace
{

// Lists of one class or input, rarely long
using ValueList_t = CUtlLeanVectorFixedGrowable< const ModelValue_t *, 32 >;
using StringList_t = CUtlLeanVectorFixedGrowable< CUtlString, 16 >;
using IntList_t = CUtlLeanVectorFixedGrowable< int, 32 >;
using NameList_t = CUtlLeanVectorFixedGrowable< const char *, 64 >;

//--------------------------------------------------------------------------------------------------
// Text helpers
//--------------------------------------------------------------------------------------------------
static const char *AppendQuoted( CBufferString &sOut, const char *pszText )
{
	sOut.Append( "\"" );

	for ( const char *p = pszText; *p; ++p )
	{
		if ( *p == '"' || *p == '\\' )
			sOut.Append( "\\" );

		sOut.Append( p, 1 );
	}

	sOut.Append( "\"" );

	return sOut.Get();
}

class CCodeWriter
{
public:
	CCodeWriter( CUtlBuffer &text ) : m_Text( text ), m_nIndent( 0 ) {}

	void Blank()
	{
		m_Text.Put( "\n", 1 );
	}

	// One line at the current indentation; data goes through %s, never into the format
	void Line( const char *pszFormat, ... ) FMTFUNCTION( 2, 3 )
	{
		CBufferStringN< 1024 > sLine;

		va_list args;
		va_start( args, pszFormat );
		sLine.AppendFormatV( pszFormat, args );
		va_end( args );

		for ( int i = 0; i < m_nIndent; ++i )
			m_Text.Put( "\t", 1 );

		m_Text.Put( sLine.Get(), sLine.Length() );
		m_Text.Put( "\n", 1 );
	}

	void Raw( const CUtlBuffer &text ) { m_Text.Put( text.Base(), text.TellPut() ); }
	void Indent() { ++m_nIndent; }
	void Unindent() { --m_nIndent; }

	void Separator( const char *pszTitle )
	{
		Line( "//--------------------------------------------------------------------------------------------------" );
		Line( "// %s", pszTitle );
		Line( "//--------------------------------------------------------------------------------------------------" );
	}

private:
	CUtlBuffer &m_Text;
	int m_nIndent;
};

void WriteBanner( CCodeWriter &writer, const char *pszSource )
{
	writer.Line( "//==================================================================================================" );
	writer.Line( "// Generated by schemacompiler " SCHEMACOMPILER_VERSION " from %s, do not edit", pszSource );
	writer.Line( "//==================================================================================================" );
}

const char *Kind( const ModelValue_t *pType ) { return Model_GetMemberString( pType, MODEL_KEY_KIND ); }
const char *Name( const ModelValue_t *pValue ) { return Model_GetMemberString( pValue, MODEL_KEY_NAME ); }
const char *Id( const ModelValue_t *pValue ) { return Model_GetMemberString( pValue, MODEL_KEY_ID ); }
const char *Cpp( const ModelValue_t *pValue ) { return Model_GetMemberString( pValue, MODEL_KEY_CPP ); }
const char *Category( const ModelValue_t *pType ) { return Model_GetMemberString( pType, MODEL_KEY_CATEGORY ); }

bool IsKind( const ModelValue_t *pType, const char *pszKind ) { return !V_strcmp( Kind( pType ), pszKind ); }
bool IsCategory( const ModelValue_t *pType, const char *pszCategory ) { return !V_strcmp( Category( pType ), pszCategory ); }
bool IsDeclared( const ModelValue_t *pType ) { return IsCategory( pType, "class" ) || IsCategory( pType, "enum" ); }

SchemaDiagLocation_t Location( const ModelValue_t *pType )
{
	return { CUtlString( Model_GetMemberString( pType, MODEL_KEY_FILE ) ), static_cast< int >( Model_GetMemberInt( pType, MODEL_KEY_LINE ) ), static_cast< int >( Model_GetMemberInt( pType, MODEL_KEY_COLUMN ) ) };
}

// Fields that go into the record, without the noschema ones
void SchemaFields( const ModelValue_t *pClass, ValueList_t &fields )
{
	const ModelValue_t *pFields = Model_Find( pClass, MODEL_KEY_FIELDS );

	for ( int i = 0; i < Model_Count( pFields ); ++i )
	{
		if ( !Model_GetMemberBool( Model_At( pFields, i ), MODEL_KEY_NOSCHEMA ) )
			fields.AddToTail( Model_At( pFields, i ) );
	}
}

bool ListContains( const StringList_t &list, const char *pszString )
{
	for ( const CUtlString &sItem : list )
	{
		if ( !V_strcmp( sItem.Get(), pszString ) )
			return true;
	}

	return false;
}

// Textual identity of a type tree, equal types share a slot
void AppendTypeKey( const ModelValue_t *pType, CBufferString &sOut )
{
	if ( IsCategory( pType, "builtin" ) )
	{
		sOut.AppendFormat( "builtin:%s", Model_GetMemberString( pType, MODEL_KEY_BUILTIN ) );
	}
	else if ( IsCategory( pType, "ptr" ) )
	{
		sOut.Append( "ptr(" );
		AppendTypeKey( Model_Find( pType, MODEL_KEY_INNER ), sOut );
		sOut.Append( ")" );
	}
	else if ( IsCategory( pType, "array" ) )
	{
		sOut.AppendFormat( "array(%lld,", static_cast< long long >( Model_GetMemberInt( pType, MODEL_KEY_COUNT ) ) );
		AppendTypeKey( Model_Find( pType, MODEL_KEY_INNER ), sOut );
		sOut.Append( ")" );
	}
	else if ( IsDeclared( pType ) )
	{
		sOut.AppendFormat( "%s:%s", Category( pType ), Name( pType ) );
	}
	else if ( IsCategory( pType, "bitfield" ) )
	{
		sOut.AppendFormat( "bitfield:%lld", static_cast< long long >( Model_GetMemberInt( pType, MODEL_KEY_BITS ) ) );
	}
	else
	{
		// Atomics differ by the full C++ type: size, alignment and arguments
		sOut.AppendFormat( "atomic:%s", Cpp( pType ) );
	}
}

//--------------------------------------------------------------------------------------------------
// Project-wide view of the models
//--------------------------------------------------------------------------------------------------
struct TypeRef_t
{
	int m_nInput = -1;
	const ModelValue_t *m_pType = nullptr;
};

class CCodegen
{
public:
	CCodegen( const SchemaProject_t &project, const CUtlLeanVector< const ModelValue_t * > &models ) :
		m_Project( project ),
		m_Models( models ),
		m_bGlobalScope( project.m_sScope == "GLOBAL" )
	{
		CBufferStringN< 128 > sId;

		m_sProjectId = project.ProjectId( sId );

		CBufferStringN< 128 > sQuotedProject;

		m_sQuotedProject = AppendQuoted( sQuotedProject, project.m_sProject.Get() );

		CBufferStringN< 256 > sImportModules;

		sImportModules.Format( "ImplSchema_ImportModules_%s", m_sProjectId.Get() );
		m_sImportModules = sImportModules.Get();

		// Inputs in path order; the order of everything generated follows it
		for ( int i = 0; i < project.m_Inputs.Count(); ++i )
			m_SortedInputs.AddToTail( i );

		Vector_Sort( m_SortedInputs, [ this ]( int a, int b ) { return V_strcmp( m_Project.m_Inputs[ a ].m_sRelative.Get(), m_Project.m_Inputs[ b ].m_sRelative.Get() ) < 0; } );
	}

	bool Generate( CUtlLeanVector< CodegenOutput_t * > &outputs );

private:
	bool CollectTypes();
	void AssignTypeSlots();
	int SlotOf( const ModelValue_t *pType ) const;

	bool IsExternal( const ModelValue_t *pType ) const;
	bool NeedsRegisterTime( const ModelValue_t *pType ) const;

	void AppendTypeExpression( const ModelValue_t *pType, const char *pszScope, const char *pszDeclScope, CBufferString &sOut ) const;
	const char *IncludeOf( const char *pszFile, const SchemaInput_t &input, bool bIncludeDirs, CBufferString &sOut ) const;
	bool MetaArray( CCodeWriter &writer, const ModelValue_t *pOwner, const char *pszArrayName, int &nCount ) const;

	void WriteClass( CCodeWriter &writer, const ModelValue_t *pClass, StringList_t &externs );
	void WriteEnum( CCodeWriter &writer, const ModelValue_t *pEnum );
	void WriteAtomic( CCodeWriter &writer, const ModelValue_t *pAtomic );
	void WriteExternalChecks( CCodeWriter &writer, const ModelValue_t *pClass, const ModelValue_t *pType, StringList_t &checked );
	bool WriteInput( int nInput, CodegenOutput_t &output );
	void WriteRegistration( CodegenOutput_t &output );

	const char *ScopeFlag() const { return m_bGlobalScope ? "SCHEMA_CF1_GLOBAL_TYPE_SCOPE" : "SCHEMA_CF1_MODULE_LOCAL_TYPE_SCOPE"; }
	const char *EnumScopeFlag() const { return m_bGlobalScope ? "SCHEMA_EF_GLOBAL_TYPE_SCOPE" : "SCHEMA_EF_MODULE_LOCAL_TYPE_SCOPE"; }

	const SchemaProject_t &m_Project;
	const CUtlLeanVector< const ModelValue_t * > &m_Models;
	const bool m_bGlobalScope;
	CUtlString m_sProjectId;
	CUtlString m_sQuotedProject;		// PROJECT_NAME of sourcesdk_target_schema as a literal
	CUtlString m_sImportModules;
	CUtlLeanVector< int > m_SortedInputs;

	CSchemaStringMap< TypeRef_t > m_Classes;
	CSchemaStringMap< TypeRef_t > m_Enums;
	CSchemaStringMap< TypeRef_t > m_Atomics;

	// Type slots: key -> slot, slot -> owner input and model of the type
	CSchemaStringMap< int > m_SlotByKey;
	CUtlLeanVector< TypeRef_t > m_Slots;

	// Inputs with an ImplSchema_TypesInit_* or an ImplSchema_ResolveExternals_*, in path order
	CUtlLeanVector< int > m_TypesInitInputs;
	CUtlLeanVector< int > m_ResolveInputs;
};

bool CCodegen::CollectTypes()
{
	bool bSuccess = true;

	for ( int nInput : m_SortedInputs )
	{
		const ModelValue_t *pTypes = Model_Find( m_Models[ nInput ], MODEL_KEY_TYPES );

		for ( int i = 0; i < Model_Count( pTypes ); ++i )
		{
			const ModelValue_t *pType = Model_At( pTypes, i );
			const CUtlString sName( Name( pType ) );

			CSchemaStringMap< TypeRef_t > &types = IsKind( pType, "class" ) ? m_Classes : IsKind( pType, "enum" ) ? m_Enums : m_Atomics;
			auto iExisting = types.Find( sName );

			if ( types.IsValidIndex( iExisting ) )
			{
				g_Diagnostics.Error( SC_DUPLICATE, Location( pType ), "%s '%s' is a schema type twice in project \"%s\"", Kind( pType ), sName.Get(), m_Project.m_sProject.Get() );
				g_Diagnostics.Note( Location( types[ iExisting ].m_pType ), "previous definition is here" );
				bSuccess = false;
				continue;
			}

			types.Insert( sName, TypeRef_t{ nInput, pType } );
		}
	}

	return bSuccess;
}

void CCodegen::AssignTypeSlots()
{
	for ( int nInput : m_SortedInputs )
	{
		const ModelValue_t *pTypes = Model_Find( m_Models[ nInput ], MODEL_KEY_TYPES );

		for ( int i = 0; i < Model_Count( pTypes ); ++i )
		{
			const ModelValue_t *pType = Model_At( pTypes, i );

			if ( !IsKind( pType, "class" ) )
				continue;

			ValueList_t fields;

			SchemaFields( pType, fields );

			for ( const ModelValue_t *pField : fields )
			{
				const ModelValue_t *pFieldType = Model_Find( pField, MODEL_KEY_TYPE );

				if ( !pFieldType || !Model_Find( pFieldType, MODEL_KEY_CATEGORY ) || NeedsRegisterTime( pFieldType ) )
					continue;

				CBufferStringN< 256 > sKey;

				AppendTypeKey( pFieldType, sKey );

				const CUtlString sStoredKey( sKey.Get() );

				if ( m_SlotByKey.IsValidIndex( m_SlotByKey.Find( sStoredKey ) ) )
					continue;

				m_SlotByKey.Insert( sStoredKey, m_Slots.AddToTail( TypeRef_t{ nInput, pFieldType } ) );
			}
		}
	}
}

int CCodegen::SlotOf( const ModelValue_t *pType ) const
{
	CBufferStringN< 256 > sKey;

	AppendTypeKey( pType, sKey );

	auto i = m_SlotByKey.Find( CUtlString( sKey.Get() ) );

	return m_SlotByKey.IsValidIndex( i ) ? m_SlotByKey[ i ] : -1;
}

// A class or enum of another module; a unit that only declares a type of this project marks it external too
bool CCodegen::IsExternal( const ModelValue_t *pType ) const
{
	if ( !Model_GetMemberBool( pType, MODEL_KEY_EXTERNAL ) )
		return false;

	const CSchemaStringMap< TypeRef_t > &types = IsCategory( pType, "enum" ) ? m_Enums : m_Classes;

	return !types.IsValidIndex( types.Find( CUtlString( Name( pType ) ) ) );
}

// A field type that names a class or enum of another module is built at registration
bool CCodegen::NeedsRegisterTime( const ModelValue_t *pType ) const
{
	if ( IsDeclared( pType ) && IsExternal( pType ) )
		return true;

	if ( const ModelValue_t *pInner = Model_Find( pType, MODEL_KEY_INNER ) )
		return NeedsRegisterTime( pInner );

	const ModelValue_t *pArgs = Model_Find( pType, MODEL_KEY_ARGS );

	for ( int i = 0; i < Model_Count( pArgs ); ++i )
	{
		const ModelValue_t *pArgType = Model_Find( Model_At( pArgs, i ), MODEL_KEY_TYPE );

		if ( pArgType && NeedsRegisterTime( pArgType ) )
			return true;
	}

	return false;
}

void CCodegen::AppendTypeExpression( const ModelValue_t *pType, const char *pszScope, const char *pszDeclScope, CBufferString &sOut ) const
{
	if ( IsCategory( pType, "builtin" ) )
	{
		sOut.AppendFormat( "%s->Type_Builtin( SCHEMA_BUILTIN_TYPE_%s ).Get()", pszScope, Model_GetMemberString( pType, MODEL_KEY_BUILTIN ) );
		return;
	}

	if ( IsCategory( pType, "ptr" ) )
	{
		sOut.AppendFormat( "%s->Type_Ptr( ", pszScope );
		AppendTypeExpression( Model_Find( pType, MODEL_KEY_INNER ), pszScope, pszDeclScope, sOut );
		sOut.Append( " ).Get()" );
		return;
	}

	if ( IsCategory( pType, "array" ) )
	{
		const char *pszElement = Cpp( pType );

		sOut.AppendFormat( "%s->Type_FixedArray( ", pszScope );
		AppendTypeExpression( Model_Find( pType, MODEL_KEY_INNER ), pszScope, pszDeclScope, sOut );
		sOut.AppendFormat( ", %lld, sizeof( %s ), alignof( %s ) ).Get()", static_cast< long long >( Model_GetMemberInt( pType, MODEL_KEY_COUNT ) ), pszElement, pszElement );
		return;
	}

	if ( IsDeclared( pType ) )
	{
		const bool bClass = IsCategory( pType, "class" );

		if ( IsExternal( pType ) )
		{
			sOut.AppendFormat( "%s( g_pSchemaSystem, ", bClass ? "SchemaGen_ExternalClassType" : "SchemaGen_ExternalEnumType" );
			AppendQuoted( sOut, Name( pType ) );
			sOut.AppendFormat( ", %s )", m_sImportModules.Get() );
		}
		else
		{
			sOut.AppendFormat( "%s->%s( ", pszDeclScope, bClass ? "Type_DeclaredClass" : "Type_DeclaredEnum" );
			AppendQuoted( sOut, Name( pType ) );
			sOut.Append( " ).Get()" );
		}

		return;
	}

	if ( IsCategory( pType, "bitfield" ) )
	{
		sOut.AppendFormat( "%s->Type_Bitfield( %lld ).Get()", pszScope, static_cast< long long >( Model_GetMemberInt( pType, MODEL_KEY_BITS ) ) );
		return;
	}

	// Atomics: the name, then size and alignment of the full type, then the arguments of the kind
	const char *pszCpp = Cpp( pType );
	const char *pszKind = Model_GetMemberString( pType, MODEL_KEY_ATOMIC_KIND );
	const ModelValue_t *pArgs = Model_Find( pType, MODEL_KEY_ARGS );

	ValueList_t typeArgs;
	const ModelValue_t *pIntArg = nullptr;

	for ( int i = 0; i < Model_Count( pArgs ); ++i )
	{
		const ModelValue_t *pArg = Model_At( pArgs, i );

		if ( Model_Find( pArg, MODEL_KEY_TYPE ) )
			typeArgs.AddToTail( pArg );
		else if ( !pIntArg )
			pIntArg = pArg;
	}

	const bool bCollection = !V_strcmp( pszKind, "collection" ) || !V_strcmp( pszKind, "collection_fixed" );
	const char *pszMethod = "Type_Atomic";
	int nTypeArgs = 0;

	if ( !V_strcmp( pszKind, "t" ) && typeArgs.Count() >= 1 )
	{
		pszMethod = "Type_Atomic_T";
		nTypeArgs = 1;
	}
	else if ( !V_strcmp( pszKind, "tt" ) && typeArgs.Count() >= 2 )
	{
		pszMethod = "Type_Atomic_TT";
		nTypeArgs = 2;
	}
	else if ( !V_strcmp( pszKind, "i" ) && pIntArg )
	{
		pszMethod = "Type_Atomic_I";
	}
	else if ( bCollection && typeArgs.Count() >= 1 )
	{
		pszMethod = "Type_Atomic_CollectionOfT";
	}

	sOut.AppendFormat( "%s->%s( ", pszScope, pszMethod );
	AppendQuoted( sOut, Model_GetMemberString( pType, MODEL_KEY_ATOMIC ) );
	sOut.AppendFormat( ", sizeof( %s ), alignof( %s )", pszCpp, pszCpp );

	if ( !V_strcmp( pszMethod, "Type_Atomic_CollectionOfT" ) )
	{
		const bool bFixed = !V_strcmp( pszKind, "collection_fixed" ) && pIntArg;

		sOut.AppendFormat( ", sizeof( %s ), ", Cpp( typeArgs[ 0 ] ) );
		AppendTypeExpression( Model_Find( typeArgs[ 0 ], MODEL_KEY_TYPE ), pszScope, pszDeclScope, sOut );
		sOut.AppendFormat( ", %lld, &%s< %s > ).Get()", bFixed ? static_cast< long long >( Model_GetMemberInt( pIntArg, MODEL_KEY_INT ) ) : 0ll, Model_GetMemberString( pType, MODEL_KEY_MANIPULATOR ), pszCpp );
		return;
	}

	for ( int i = 0; i < nTypeArgs; ++i )
	{
		sOut.Append( ", " );
		AppendTypeExpression( Model_Find( typeArgs[ i ], MODEL_KEY_TYPE ), pszScope, pszDeclScope, sOut );
	}

	if ( !V_strcmp( pszMethod, "Type_Atomic_I" ) )
		sOut.AppendFormat( ", %lld", static_cast< long long >( Model_GetMemberInt( pIntArg, MODEL_KEY_INT ) ) );

	sOut.Append( " ).Get()" );
}

// Through an include directory of the target when one covers the file, else relative to the output
const char *CCodegen::IncludeOf( const char *pszFile, const SchemaInput_t &input, bool bIncludeDirs, CBufferString &sOut ) const
{
	sOut.Clear();

	if ( bIncludeDirs )
	{
		for ( const CUtlString &sInclude : m_Project.m_Includes )
		{
			CSchemaPathString sRelative;

			if ( !Path_IsUnder( pszFile, sInclude.Get() ) || !Path_Relative( pszFile, sInclude.Get(), sRelative ) )
				continue;

			// The most qualified spelling, e.g. "kv3lib/kv3transfer_schema.h" rather than "kv3transfer_schema.h"
			if ( sOut.Length() == 0 || sRelative.Length() > sOut.Length() )
				sOut.Set( sRelative.Get() );
		}
	}

	if ( sOut.Length() == 0 )
	{
		CSchemaPathString sDirectory;

		if ( !Path_Relative( pszFile, Path_Directory( input.m_sOutput.Get(), sDirectory ), sOut ) )
			sOut.Set( pszFile );
	}

	return sOut.Get();
}

// Declaration files of the tags with a value; their Storage_t types are named in the records
void CollectTagFiles( const ModelValue_t *pOwner, StringList_t &files )
{
	const ModelValue_t *pMeta = Model_Find( pOwner, MODEL_KEY_META );

	for ( int i = 0; i < Model_Count( pMeta ); ++i )
	{
		const ModelValue_t *pEntry = Model_At( pMeta, i );
		const char *pszFile = Model_GetMemberString( pEntry, MODEL_KEY_FILE );

		if ( Model_Find( pEntry, MODEL_KEY_VALUE ) && !Model_GetMemberBool( pEntry, MODEL_KEY_CODEGEN ) && *pszFile && !ListContains( files, pszFile ) )
			files.AddToTail( CUtlString( pszFile ) );
	}

	for ( ModelKey_t eKey : { MODEL_KEY_FIELDS, MODEL_KEY_ENUMERATORS } )
	{
		const ModelValue_t *pChildren = Model_Find( pOwner, eKey );

		for ( int i = 0; i < Model_Count( pChildren ); ++i )
			CollectTagFiles( Model_At( pChildren, i ), files );
	}
}

// Static values and the entry array of a metadata list; false without entries
bool CCodegen::MetaArray( CCodeWriter &writer, const ModelValue_t *pOwner, const char *pszArrayName, int &nCount ) const
{
	const ModelValue_t *pMeta = Model_Find( pOwner, MODEL_KEY_META );
	StringList_t entries;

	for ( int i = 0; i < Model_Count( pMeta ); ++i )
	{
		const ModelValue_t *pEntry = Model_At( pMeta, i );

		if ( Model_GetMemberBool( pEntry, MODEL_KEY_CODEGEN ) )
			continue;

		const char *pszTag = Name( pEntry );
		const ModelValue_t *pValue = Model_Find( pEntry, MODEL_KEY_VALUE );

		CBufferStringN< 256 > sEntry;

		if ( pValue )
		{
			CBufferStringN< 256 > sValueName;

			sValueName.Format( "%s%d_%s_Value", pszArrayName, entries.Count(), pszTag );

			writer.Line( "static %s::Storage_t %s = %s;", pszTag, sValueName.Get(), Model_GetString( pValue ) );
			writer.Blank();
			sEntry.Format( "{ \"%s\", &%s }", pszTag, sValueName.Get() );
		}
		else
		{
			sEntry.Format( "{ \"%s\", nullptr }", pszTag );
		}

		entries.AddToTail( CUtlString( sEntry.Get() ) );
	}

	nCount = entries.Count();

	if ( !nCount )
		return false;

	writer.Line( "static SchemaMetadataEntryData_t %s[] =", pszArrayName );
	writer.Line( "{" );
	writer.Indent();

	for ( const CUtlString &sEntry : entries )
		writer.Line( "%s,", sEntry.Get() );

	writer.Unindent();
	writer.Line( "};" );
	writer.Blank();

	return true;
}

void CCodegen::WriteClass( CCodeWriter &writer, const ModelValue_t *pClass, StringList_t &externs )
{
	const char *pszName = Name( pClass );
	const char *pszId = Id( pClass );
	const char *pszCpp = Cpp( pClass );

	CBufferStringN< 256 > sAlias, sInfo, sMembers, sBases;

	sAlias.Format( "ImplSchema_Class_%s", pszId );
	sInfo.Format( "ImplSchema_ClassInfo_%s", pszId );
	sMembers.Format( "ImplSchema_ClassMembers_%s", pszId );
	sBases.Format( "ImplSchema_ClassBases_%s", pszId );

	writer.Separator( pszName );
	writer.Line( "using %s = %s;", sAlias.Get(), pszCpp );
	writer.Blank();
	writer.Line( "extern SCHEMAGEN_LOCAL CSchemaClassInfo %s;", sInfo.Get() );

	const ModelValue_t *pBases = Model_Find( pClass, MODEL_KEY_BASES );

	for ( int i = 0; i < Model_Count( pBases ); ++i )
	{
		const ModelValue_t *pBase = Model_At( pBases, i );

		// Also for a base later in this unit, the array below takes its address
		if ( !IsExternal( pBase ) && !ListContains( externs, Id( pBase ) ) )
		{
			externs.AddToTail( CUtlString( Id( pBase ) ) );
			writer.Line( "extern SCHEMAGEN_LOCAL CSchemaClassInfo ImplSchema_ClassInfo_%s;", Id( pBase ) );
		}
	}

	writer.Blank();

	ValueList_t fields;

	SchemaFields( pClass, fields );

	// Access to the private and protected fields
	bool bAccessors = false;

	for ( const ModelValue_t *pField : fields )
	{
		if ( !V_strcmp( Model_GetMemberString( pField, MODEL_KEY_ACCESS ), "public" ) || Model_Find( pField, MODEL_KEY_OFFSET ) )
			continue;

		CBufferStringN< 256 > sTag;

		sTag.Format( "SchemaGenAccess_%s_%s", pszId, Name( pField ) );

		writer.Line( "struct %s { using Type_t = SchemaGen_MemberPtr_t< %s, %s >; friend Type_t SchemaGen_MemberPointer( %s ); };", sTag.Get(), Cpp( pField ), sAlias.Get(), sTag.Get() );
		writer.Line( "template struct CSchemaGenMemberAccess< %s, &%s::%s >;", sTag.Get(), pszCpp, Name( pField ) );
		bAccessors = true;
	}

	if ( bAccessors )
		writer.Blank();

	// Metadata
	CBufferStringN< 256 > sClassMeta;
	int nClassMeta = 0;

	sClassMeta.Format( "ImplSchema_ClassMeta_%s", pszId );

	if ( !MetaArray( writer, pClass, sClassMeta.Get(), nClassMeta ) )
		sClassMeta.Set( "nullptr" );

	StringList_t fieldMeta;
	IntList_t fieldMetaCounts;

	for ( const ModelValue_t *pField : fields )
	{
		CBufferStringN< 256 > sFieldMeta;
		int nCount = 0;

		sFieldMeta.Format( "ImplSchema_FieldMeta_%s_%s", pszId, Name( pField ) );

		if ( !MetaArray( writer, pField, sFieldMeta.Get(), nCount ) )
			sFieldMeta.Set( "nullptr" );

		fieldMeta.AddToTail( CUtlString( sFieldMeta.Get() ) );
		fieldMetaCounts.AddToTail( nCount );
	}

	// Fields
	IntList_t registerFields, accessFields;

	if ( fields.Count() > 0 )
	{
		writer.Line( "static SchemaClassFieldData_t %s[] =", sMembers.Get() );
		writer.Line( "{" );
		writer.Indent();

		for ( int i = 0; i < fields.Count(); ++i )
		{
			const ModelValue_t *pField = fields[ i ];
			const ModelValue_t *pFieldType = Model_Find( pField, MODEL_KEY_TYPE );

			CBufferStringN< 64 > sType( "nullptr" );

			if ( pFieldType && Model_Find( pFieldType, MODEL_KEY_CATEGORY ) )
			{
				if ( NeedsRegisterTime( pFieldType ) )
					registerFields.AddToTail( i );
				else
					sType.Format( "SCHEMAGEN_TYPE_SLOT( %d )", SlotOf( pFieldType ) );
			}

			CBufferStringN< 256 > sOffset;

			if ( const ModelValue_t *pOffset = Model_Find( pField, MODEL_KEY_OFFSET ) )
			{
				// A bit-field has no offsetof, the parser layout gives its storage unit
				sOffset.Format( "%lld", static_cast< long long >( Model_GetInt( pOffset ) ) );
			}
			else if ( !V_strcmp( Model_GetMemberString( pField, MODEL_KEY_ACCESS ), "public" ) )
			{
				sOffset.Format( "offsetof( %s, %s )", sAlias.Get(), Name( pField ) );
			}
			else
			{
				sOffset.Set( "0" );
				accessFields.AddToTail( i );
			}

			writer.Line( "{ \"%s\", %s, %s, %d, %s },", Name( pField ), sType.Get(), sOffset.Get(), fieldMetaCounts[ i ], fieldMeta[ i ].Get() );
		}

		writer.Unindent();
		writer.Line( "};" );
		writer.Blank();
	}

	// Bases; those of other modules are found before the classes register
	if ( Model_Count( pBases ) > 0 )
	{
		writer.Line( "static SchemaBaseClassInfoData_t %s[] =", sBases.Get() );
		writer.Line( "{" );
		writer.Indent();

		for ( int i = 0; i < Model_Count( pBases ); ++i )
		{
			const ModelValue_t *pBase = Model_At( pBases, i );

			if ( IsExternal( pBase ) )
				writer.Line( "{ 0, nullptr }, // %s of another module", Name( pBase ) );
			else
				writer.Line( "{ 0, &ImplSchema_ClassInfo_%s },", Id( pBase ) );
		}

		writer.Unindent();
		writer.Line( "};" );
		writer.Blank();
	}

	// Manipulator: registration fills the remaining types, offsets of private fields and base offsets
	writer.Line( "static void *ImplSchema_ClassOps_%s( SchemaClassManipulatorAction_t eAction, void *pObject )", pszId );
	writer.Line( "{" );
	writer.Indent();
	writer.Line( "if ( eAction == SCHEMA_CLASS_MANIPULATOR_ACTION_REGISTER )" );

	if ( registerFields.Count() == 0 && accessFields.Count() == 0 && Model_Count( pBases ) == 0 )
	{
		writer.Indent();
		writer.Line( "return pObject;" );
		writer.Unindent();
	}
	else
	{
		writer.Line( "{" );
		writer.Indent();

		if ( registerFields.Count() > 0 )
		{
			writer.Line( "CSchemaSystemTypeScope *pScope = static_cast< CSchemaClassInfo * >( pObject )->m_pTypeScope;" );
			writer.Blank();

			for ( int nField : registerFields )
			{
				CBufferStringN< 512 > sExpression;

				AppendTypeExpression( Model_Find( fields[ nField ], MODEL_KEY_TYPE ), "pScope", "pScope", sExpression );
				writer.Line( "%s[ %d ].m_pType = %s;", sMembers.Get(), nField, sExpression.Get() );
			}
		}

		for ( int nField : accessFields )
			writer.Line( "%s[ %d ].m_nSingleInheritanceOffset = SchemaGen_MemberOffset( SchemaGen_MemberPointer( SchemaGenAccess_%s_%s() ) );", sMembers.Get(), nField, pszId, Name( fields[ nField ] ) );

		for ( int i = 0; i < Model_Count( pBases ); ++i )
			writer.Line( "%s[ %d ].m_nOffset = SchemaGen_BaseOffset< %s, %s >();", sBases.Get(), i, sAlias.Get(), Cpp( Model_At( pBases, i ) ) );

		writer.Blank();
		writer.Line( "return pObject;" );
		writer.Unindent();
		writer.Line( "}" );
	}

	writer.Blank();
	writer.Line( "if ( eAction == SCHEMA_CLASS_MANIPULATOR_ACTION_REGISTER_PRE )" );
	writer.Indent();
	writer.Line( "return nullptr;" );
	writer.Unindent();
	writer.Blank();
	writer.Line( "return SchemaGen_ClassManipulator< %s >( eAction, pObject, %s );", sAlias.Get(), sInfo.Get() );
	writer.Unindent();
	writer.Line( "}" );
	writer.Blank();

	// Flags: traits of the class, the project scope and the tags kept as bits
	CBufferStringN< 512 > sFlags;

	sFlags.Format( "SchemaGen_ClassFlags1< %s >() | %s", sAlias.Get(), ScopeFlag() );

	const ModelValue_t *pFlagTags = Model_Find( pClass, MODEL_KEY_FLAG_TAGS );

	for ( int i = 0; i < Model_Count( pFlagTags ); ++i )
		sFlags.AppendFormat( " | SCHEMA_CF1_INFO_TAG_%s", Model_GetString( Model_At( pFlagTags, i ) ) );

	CBufferStringN< 256 > sQuotedName, sQuotedCpp;

	AppendQuoted( sQuotedName, pszName );

	writer.Line( "SCHEMAGEN_LOCAL CSchemaClassInfo %s =", sInfo.Get() );
	writer.Line( "{ {" );
	writer.Indent();
	writer.Line( "nullptr, // m_pSchemaBinding" );
	writer.Line( "%s, // m_pszName", sQuotedName.Get() );
	writer.Line( "%s, // m_pszProjectName", m_sQuotedProject.Get() );
	writer.Line( "%s, // m_pszCPPName", AppendQuoted( sQuotedCpp, pszCpp + ( String_StartsWith( pszCpp, "::" ) ? 2 : 0 ) ) );
	writer.Line( "sizeof( %s ), // m_nSize", sAlias.Get() );
	writer.Line( "%d, // m_nFieldCount", fields.Count() );
	writer.Line( "%d, // m_nStaticMetadataCount", nClassMeta );
	writer.Line( "alignof( %s ), // m_nAlignment", sAlias.Get() );
	writer.Line( "%d, // m_nBaseClassCount", Model_Count( pBases ) );
	writer.Line( "0xFFFF, // m_nMultipleInheritanceDepth" );
	writer.Line( "0xFFFF, // m_nSingleInheritanceDepth" );
	writer.Line( "%s, // m_pFields", fields.Count() > 0 ? sMembers.Get() : "nullptr" );
	writer.Line( "%s, // m_pBaseClasses", Model_Count( pBases ) > 0 ? sBases.Get() : "nullptr" );
	writer.Line( "nullptr, // m_pDataMap" );
	writer.Line( "%s, // m_pStaticMetadata", sClassMeta.Get() );
	writer.Line( "nullptr, // m_pTypeScope" );
	writer.Line( "nullptr, // m_pDeclaredClass" );
	writer.Line( "%s, // m_nFlags1", sFlags.Get() );
	writer.Line( "0, // m_nFlags2" );
	writer.Line( "&ImplSchema_ClassOps_%s, // m_pfnManipulator", pszId );
	writer.Unindent();
	writer.Line( "} };" );
	writer.Blank();

	// A declared Schema_DynamicBinding without a body gets its definition here
	if ( !V_strcmp( Model_GetMemberString( pClass, MODEL_KEY_DYNAMIC_BINDING ), "declared" ) )
	{
		writer.Line( "%s %s::Schema_DynamicBinding()", Model_GetMemberString( pClass, MODEL_KEY_RETURN_TYPE ), pszCpp );
		writer.Line( "{" );
		writer.Indent();
		writer.Line( "return %s.m_pSchemaBinding;", sInfo.Get() );
		writer.Unindent();
		writer.Line( "}" );
		writer.Blank();
	}
}

void CCodegen::WriteEnum( CCodeWriter &writer, const ModelValue_t *pEnum )
{
	const char *pszName = Name( pEnum );
	const char *pszId = Id( pEnum );
	const char *pszCpp = Cpp( pEnum );

	CBufferStringN< 256 > sMembers, sEnumMeta, sQuotedName;

	sMembers.Format( "ImplSchema_EnumMembersOf_%s", pszId );
	sEnumMeta.Format( "ImplSchema_EnumMeta_%s", pszId );
	AppendQuoted( sQuotedName, pszName );

	writer.Separator( pszName );

	int nEnumMeta = 0;

	if ( !MetaArray( writer, pEnum, sEnumMeta.Get(), nEnumMeta ) )
		sEnumMeta.Set( "nullptr" );

	const ModelValue_t *pEnumerators = Model_Find( pEnum, MODEL_KEY_ENUMERATORS );
	StringList_t meta;
	IntList_t metaCounts;

	for ( int i = 0; i < Model_Count( pEnumerators ); ++i )
	{
		const ModelValue_t *pEnumerator = Model_At( pEnumerators, i );

		CBufferStringN< 256 > sMeta;
		int nCount = 0;

		sMeta.Format( "ImplSchema_EnumeratorMeta_%s_%s", pszId, Name( pEnumerator ) );

		if ( !MetaArray( writer, pEnumerator, sMeta.Get(), nCount ) )
			sMeta.Set( "nullptr" );

		meta.AddToTail( CUtlString( sMeta.Get() ) );
		metaCounts.AddToTail( nCount );
	}

	if ( Model_Count( pEnumerators ) > 0 )
	{
		writer.Line( "static SchemaEnumeratorInfoData_t %s[] =", sMembers.Get() );
		writer.Line( "{" );
		writer.Indent();

		for ( int i = 0; i < Model_Count( pEnumerators ); ++i )
		{
			const ModelValue_t *pEnumerator = Model_At( pEnumerators, i );

			writer.Line( "{ \"%s\", static_cast< int64 >( %s::%s ), %d, %s },", Name( pEnumerator ), pszCpp, Name( pEnumerator ), metaCounts[ i ], meta[ i ].Get() );
		}

		writer.Unindent();
		writer.Line( "};" );
		writer.Blank();
	}

	// The range as expressions of the enumerators, like the array; -1 for an enum without them
	CBufferStringN< 256 > sMin( "-1" ), sMax( "-1" );
	const ModelValue_t *pMin = nullptr, *pMax = nullptr;

	for ( int i = 0; i < Model_Count( pEnumerators ); ++i )
	{
		const ModelValue_t *pEnumerator = Model_At( pEnumerators, i );
		const int64 nValue = Model_GetMemberInt( pEnumerator, MODEL_KEY_VALUE );

		if ( !pMin || nValue < Model_GetMemberInt( pMin, MODEL_KEY_VALUE ) )
			pMin = pEnumerator;

		if ( !pMax || nValue > Model_GetMemberInt( pMax, MODEL_KEY_VALUE ) )
			pMax = pEnumerator;
	}

	if ( pMin && pMax )
	{
		sMin.Format( "static_cast< int64 >( %s::%s )", pszCpp, Name( pMin ) );
		sMax.Format( "static_cast< int64 >( %s::%s )", pszCpp, Name( pMax ) );
	}

	writer.Line( "SCHEMAGEN_LOCAL CSchemaEnumInfo ImplSchema_EnumInfo_%s =", pszId );
	writer.Line( "{ {" );
	writer.Indent();
	writer.Line( "nullptr, // m_pSchemaBinding" );
	writer.Line( "%s, // m_pszName", sQuotedName.Get() );
	writer.Line( "%s, // m_pszProjectName", m_sQuotedProject.Get() );
	writer.Line( "sizeof( %s ), // m_nSize", pszCpp );
	writer.Line( "alignof( %s ), // m_nAlignment", pszCpp );
	writer.Line( "%s, // m_nFlags", EnumScopeFlag() );
	writer.Line( "%d, // m_nEnumeratorCount", Model_Count( pEnumerators ) );
	writer.Line( "%d, // m_nStaticMetadataCount", nEnumMeta );
	writer.Line( "%s, // m_pEnumerators", Model_Count( pEnumerators ) > 0 ? sMembers.Get() : "nullptr" );
	writer.Line( "%s, // m_pStaticMetadata", sEnumMeta.Get() );
	writer.Line( "nullptr, // m_pTypeScope" );
	writer.Line( "%s, // m_nMinEnumeratorValue", sMin.Get() );
	writer.Line( "%s, // m_nMaxEnumeratorValue", sMax.Get() );
	writer.Unindent();
	writer.Line( "} };" );
	writer.Blank();
}

void CCodegen::WriteAtomic( CCodeWriter &writer, const ModelValue_t *pAtomic )
{
	const char *pszName = Name( pAtomic );
	const char *pszId = Id( pAtomic );

	CBufferStringN< 256 > sTitle, sMeta;

	sTitle.Format( Model_GetMemberBool( pAtomic, MODEL_KEY_TEMPLATE ) ? "%s< ... >" : "%s", pszName );
	sMeta.Format( "ImplSchema_AtomicMeta2_%s", pszId );

	writer.Separator( sTitle.Get() );

	int nMeta = 0;

	if ( !MetaArray( writer, pAtomic, sMeta.Get(), nMeta ) )
		sMeta.Set( "nullptr" );

	// m_nAtomicID is CSchemaType_Hash of the name
	const uint32 nId = MurmurHash2( pszName, V_strlen( pszName ), 0xBAADFEED );

	writer.Line( "SCHEMAGEN_LOCAL SchemaAtomicTypeInfo_t ImplSchema_AtomicInfo_%s =", pszId );
	writer.Line( "{" );
	writer.Indent();
	writer.Line( "\"%s\", // m_pszName", pszName );
	writer.Line( "\"%s\", // m_pszTokenName", pszName );
	writer.Line( "static_cast< int >( 0x%08Xu ), // m_nAtomicID", nId );
	writer.Line( "%d, // m_nStaticMetadataCount", nMeta );
	writer.Line( "%s, // m_pStaticMetadata", sMeta.Get() );
	writer.Unindent();
	writer.Line( "};" );
	writer.Blank();
}

// Field types of other modules must exist before the manipulator builds them
void CCodegen::WriteExternalChecks( CCodeWriter &writer, const ModelValue_t *pClass, const ModelValue_t *pType, StringList_t &checked )
{
	if ( IsDeclared( pType ) && IsExternal( pType ) )
	{
		CBufferStringN< 256 > sKey;

		sKey.Format( "%s:%s", Category( pType ), Name( pType ) );

		if ( !ListContains( checked, sKey.Get() ) )
		{
			checked.AddToTail( CUtlString( sKey.Get() ) );

			writer.Line( "if ( !%s( pSchemaSystem, \"%s\", %s ) )", IsCategory( pType, "class" ) ? "SchemaGen_FindClass" : "SchemaGen_FindEnum", Name( pType ), m_sImportModules.Get() );
			writer.Line( "{" );
			writer.Indent();
			writer.Line( "SchemaGen_AppendFailure( pFailureReason, \"%s\", \"%s\", \"%s %s\" );", m_Project.m_sProject.Get(), Name( pClass ), Category( pType ), Name( pType ) );
			writer.Line( "bResolved = false;" );
			writer.Unindent();
			writer.Line( "}" );
			writer.Blank();
		}
	}

	if ( const ModelValue_t *pInner = Model_Find( pType, MODEL_KEY_INNER ) )
		WriteExternalChecks( writer, pClass, pInner, checked );

	const ModelValue_t *pArgs = Model_Find( pType, MODEL_KEY_ARGS );

	for ( int i = 0; i < Model_Count( pArgs ); ++i )
	{
		if ( const ModelValue_t *pArgType = Model_Find( Model_At( pArgs, i ), MODEL_KEY_TYPE ) )
			WriteExternalChecks( writer, pClass, pArgType, checked );
	}
}

bool CCodegen::WriteInput( int nInput, CodegenOutput_t &output )
{
	const SchemaInput_t &input = m_Project.m_Inputs[ nInput ];
	const ModelValue_t *pModel = m_Models[ nInput ];
	const ModelValue_t *pTypes = Model_Find( pModel, MODEL_KEY_TYPES );

	bool bSuccess = true;
	CCodeWriter writer( output.m_Text );
	CUtlBuffer codegen;

	// Entry points first: the unit declares and defines only those with a body
	CUtlBuffer typesInit, resolve;
	CCodeWriter typesInitWriter( typesInit ), resolveWriter( resolve );

	typesInitWriter.Indent();
	resolveWriter.Indent();

	// Slots of the project type table this input owns
	for ( int nSlot = 0; nSlot < m_Slots.Count(); ++nSlot )
	{
		if ( m_Slots[ nSlot ].m_nInput != nInput )
			continue;

		CBufferStringN< 512 > sExpression;

		AppendTypeExpression( m_Slots[ nSlot ].m_pType, "pScope", "pDeclScope", sExpression );
		typesInitWriter.Line( "ppTypes[ %d ] = %s;", nSlot, sExpression.Get() );
	}

	// Bases and field types of other modules; false makes the registrar retry the phase
	for ( int i = 0; i < Model_Count( pTypes ); ++i )
	{
		const ModelValue_t *pType = Model_At( pTypes, i );

		if ( !IsKind( pType, "class" ) )
			continue;

		const ModelValue_t *pBases = Model_Find( pType, MODEL_KEY_BASES );

		for ( int j = 0; j < Model_Count( pBases ); ++j )
		{
			const ModelValue_t *pBase = Model_At( pBases, j );

			if ( !IsExternal( pBase ) )
				continue;

			CBufferStringN< 256 > sSlot;

			sSlot.Format( "ImplSchema_ClassBases_%s[ %d ].m_pClass", Id( pType ), j );

			resolveWriter.Line( "if ( !%s && !( %s = SchemaGen_FindClass( pSchemaSystem, \"%s\", %s ) ) )", sSlot.Get(), sSlot.Get(), Name( pBase ), m_sImportModules.Get() );
			resolveWriter.Line( "{" );
			resolveWriter.Indent();
			resolveWriter.Line( "SchemaGen_AppendFailure( pFailureReason, \"%s\", \"%s\", \"base class %s\" );", m_Project.m_sProject.Get(), Name( pType ), Name( pBase ) );
			resolveWriter.Line( "bResolved = false;" );
			resolveWriter.Unindent();
			resolveWriter.Line( "}" );
			resolveWriter.Blank();
		}

		ValueList_t fields;
		StringList_t checked;

		SchemaFields( pType, fields );

		for ( const ModelValue_t *pField : fields )
		{
			if ( const ModelValue_t *pFieldType = Model_Find( pField, MODEL_KEY_TYPE ) )
				WriteExternalChecks( resolveWriter, pType, pFieldType, checked );
		}
	}

	if ( typesInit.TellPut() > 0 )
		m_TypesInitInputs.AddToTail( nInput );

	if ( resolve.TellPut() > 0 )
		m_ResolveInputs.AddToTail( nInput );

	WriteBanner( writer, input.m_sRelative.Get() );

	// The unit sees the input as the parser did: the prefix first, for headers that are not self-contained
	if ( m_Project.m_PreIncludes.Count() > 0 || !m_Project.m_sPch.IsEmpty() )
	{
		for ( const CUtlString &sPreInclude : m_Project.m_PreIncludes )
			writer.Line( "#include \"%s\"", sPreInclude.Get() );

		if ( !m_Project.m_sPch.IsEmpty() )
			writer.Line( "#include \"%s\"", m_Project.m_sPch.Get() );

		writer.Blank();
	}

	writer.Line( "#include \"schemasystem/schemagen.h\"" );

	StringList_t tagFiles;

	for ( int i = 0; i < Model_Count( pTypes ); ++i )
		CollectTagFiles( Model_At( pTypes, i ), tagFiles );

	Vector_Sort( tagFiles, []( const CUtlString &sLeft, const CUtlString &sRight ) { return V_strcmp( sLeft.Get(), sRight.Get() ) < 0; } );

	for ( const CUtlString &sTagFile : tagFiles )
	{
		CSchemaPathString sInclude;

		writer.Line( "#include \"%s\"", IncludeOf( sTagFile.Get(), input, true, sInclude ) );
	}

	CSchemaPathString sInputInclude;

	writer.Line( "#include \"%s\"", IncludeOf( input.m_sInput.Get(), input, !input.m_bIsCpp, sInputInclude ) );
	writer.Blank();
	writer.Line( "// Generated for schema binding version %d, rerun schemacompiler if this fails", SCHEMACOMPILER_BINDING_VERSION );
	writer.Line( "COMPILE_TIME_ASSERT( SCHEMA_BINDING_VERSION == %d );", SCHEMACOMPILER_BINDING_VERSION );
	writer.Blank();

	if ( resolve.TellPut() > 0 )
	{
		writer.Line( "extern SCHEMAGEN_LOCAL const char *const %s[];", m_sImportModules.Get() );
		writer.Blank();
	}

	StringList_t externs;

	for ( int i = 0; i < Model_Count( pTypes ); ++i )
	{
		const ModelValue_t *pType = Model_At( pTypes, i );

		if ( IsKind( pType, "class" ) )
		{
			WriteClass( writer, pType, externs );

			// Codegen tag scripts, the methods they define go into this unit
			const ModelValue_t *pCodegen = m_Project.m_bEmitCodegen ? Model_Find( pType, MODEL_KEY_CODEGEN ) : nullptr;

			for ( int j = 0; j < Model_Count( pCodegen ); ++j )
			{
				const char *pszTag = Model_GetString( Model_At( pCodegen, j ) );
				CCodeWriter codegenWriter( codegen );

				codegenWriter.Line( "// %s: %s", pszTag, Name( pType ) );

				if ( !Script_EmitClass( pType, Model_Find( pModel, MODEL_KEY_CODEGEN_TAGS ), pszTag, codegen ) )
					bSuccess = false;

				codegenWriter.Blank();
			}
		}
		else if ( IsKind( pType, "enum" ) )
		{
			WriteEnum( writer, pType );
		}
		else
		{
			WriteAtomic( writer, pType );
		}
	}

	if ( typesInit.TellPut() > 0 || resolve.TellPut() > 0 )
		writer.Separator( "Registration entry points" );

	if ( typesInit.TellPut() > 0 )
	{
		writer.Line( "void ImplSchema_TypesInit_%s( CSchemaSystemTypeScope *pScope, CSchemaSystemTypeScope *pDeclScope, CSchemaType **ppTypes )", input.m_sId.Get() );
		writer.Line( "{" );
		writer.Raw( typesInit );
		writer.Line( "}" );
	}

	if ( resolve.TellPut() > 0 )
	{
		if ( typesInit.TellPut() > 0 )
			writer.Blank();

		writer.Line( "bool ImplSchema_ResolveExternals_%s( ISchemaSystem *pSchemaSystem, CBufferString *pFailureReason )", input.m_sId.Get() );
		writer.Line( "{" );
		writer.Indent();
		writer.Line( "bool bResolved = true;" );
		writer.Blank();
		writer.Unindent();
		writer.Raw( resolve );
		writer.Indent();
		writer.Line( "return bResolved;" );
		writer.Unindent();
		writer.Line( "}" );
	}

	if ( codegen.TellPut() > 0 )
	{
		writer.Blank();
		writer.Separator( "Codegen tags" );
		writer.Raw( codegen );
	}

	// The input .cpp is compiled through this unit, its own target entry is header-only
	output.m_sPath = input.m_sOutput;

	return bSuccess;
}

void CCodegen::WriteRegistration( CodegenOutput_t &output )
{
	const char *pszId = m_sProjectId.Get();
	const char *pszProject = m_Project.m_sProject.Get();
	const int nTypes = Max( 1, m_Slots.Count() );

	CBufferStringN< 256 > sTypes, sClassTable, sEnumTable, sAtomicTable, sAnchor, sRegistration, sSource;

	sTypes.Format( "ImplSchema_ProjectTypes_%s", pszId );
	sClassTable.Format( "ImplSchema_ClassTable_%s", pszId );
	sEnumTable.Format( "ImplSchema_EnumTable_%s", pszId );
	sAtomicTable.Format( "ImplSchema_AtomicTable_%s", pszId );
	sAnchor.Format( "g_nLinkerHack_SchemaAnchor_RegistrationCountFor_%s", pszId );
	sRegistration.Format( "CSchemaRegistration_%s", pszId );
	sSource.Format( "project %s (target %s)", pszProject, m_Project.m_sTarget.Get() );

	CCodeWriter writer( output.m_Text );

	WriteBanner( writer, sSource.Get() );
	writer.Line( "#include \"schemasystem/schemagen.h\"" );
	writer.Blank();
	writer.Line( "// Generated for schema binding version %d, rerun schemacompiler if this fails", SCHEMACOMPILER_BINDING_VERSION );
	writer.Line( "COMPILE_TIME_ASSERT( SCHEMA_BINDING_VERSION == %d );", SCHEMACOMPILER_BINDING_VERSION );
	writer.Blank();

	// Bases before their derived classes, RegisterClasses needs the base bindings first
	// Ids and names point into the models, which outlive the codegen
	NameList_t classIds, enumIds, atomicIds, visited;

	for ( auto i = m_Enums.FirstInorder(); m_Enums.IsValidIndex( i ); i = m_Enums.NextInorder( i ) )
		enumIds.AddToTail( Id( m_Enums[ i ].m_pType ) );

	for ( auto i = m_Atomics.FirstInorder(); m_Atomics.IsValidIndex( i ); i = m_Atomics.NextInorder( i ) )
		atomicIds.AddToTail( Id( m_Atomics[ i ].m_pType ) );

	struct CClassOrder
	{
		const CSchemaStringMap< TypeRef_t > &m_Classes;
		NameList_t &m_Visited;
		NameList_t &m_Ids;

		void Add( const char *pszName )
		{
			for ( const char *pszVisited : m_Visited )
			{
				if ( !V_strcmp( pszVisited, pszName ) )
					return;
			}

			m_Visited.AddToTail( pszName );

			auto i = m_Classes.Find( CUtlString( pszName ) );

			if ( !m_Classes.IsValidIndex( i ) )
				return;

			const ModelValue_t *pClass = m_Classes[ i ].m_pType;
			const ModelValue_t *pBases = Model_Find( pClass, MODEL_KEY_BASES );

			for ( int j = 0; j < Model_Count( pBases ); ++j )
			{
				// Bases of other modules are not in m_Classes, Add skips them
				Add( Name( Model_At( pBases, j ) ) );
			}

			m_Ids.AddToTail( Id( pClass ) );
		}
	}
	order{ m_Classes, visited, classIds };

	for ( auto i = m_Classes.FirstInorder(); m_Classes.IsValidIndex( i ); i = m_Classes.NextInorder( i ) )
		order.Add( m_Classes.Key( i ).Get() );

	auto WriteExterns = [ &writer ]( const char *pszType, const char *pszPrefix, const NameList_t &ids )
	{
		for ( const char *pszTypeId : ids )
			writer.Line( "extern SCHEMAGEN_LOCAL %s %s%s;", pszType, pszPrefix, pszTypeId );

		if ( ids.Count() > 0 )
			writer.Blank();
	};

	WriteExterns( "CSchemaClassInfo", "ImplSchema_ClassInfo_", classIds );
	WriteExterns( "CSchemaEnumInfo", "ImplSchema_EnumInfo_", enumIds );
	WriteExterns( "SchemaAtomicTypeInfo_t", "ImplSchema_AtomicInfo_", atomicIds );

	// Entry points of the inputs that have them
	for ( int nInput : m_TypesInitInputs )
		writer.Line( "void ImplSchema_TypesInit_%s( CSchemaSystemTypeScope *pScope, CSchemaSystemTypeScope *pDeclScope, CSchemaType **ppTypes );", m_Project.m_Inputs[ nInput ].m_sId.Get() );

	if ( m_TypesInitInputs.Count() > 0 )
		writer.Blank();

	for ( int nInput : m_ResolveInputs )
		writer.Line( "bool ImplSchema_ResolveExternals_%s( ISchemaSystem *pSchemaSystem, CBufferString *pFailureReason );", m_Project.m_Inputs[ nInput ].m_sId.Get() );

	if ( m_ResolveInputs.Count() > 0 )
		writer.Blank();

	// Module file names whose type scopes are searched for classes of other modules
	if ( m_ResolveInputs.Count() > 0 )
	{
		writer.Line( "SCHEMAGEN_LOCAL const char *const %s[] =", m_sImportModules.Get() );
		writer.Line( "{" );
		writer.Indent();

		for ( const CUtlString &sModule : m_Project.m_ImportModules )
		{
			CBufferStringN< 256 > sQuoted;

			writer.Line( "%s,", AppendQuoted( sQuoted, sModule.Get() ) );
		}

		writer.Line( "nullptr," );
		writer.Unindent();
		writer.Line( "};" );
		writer.Blank();
	}

	writer.Line( "static CSchemaType *%s[ %d ];", sTypes.Get(), nTypes );
	writer.Blank();

	auto WriteTable = [ & ]( const char *pszType, const char *pszTable, const char *pszPrefix, const NameList_t &ids )
	{
		writer.Line( "static %s *%s[] =", pszType, pszTable );
		writer.Line( "{" );
		writer.Indent();

		for ( const char *pszTypeId : ids )
			writer.Line( "&%s%s,", pszPrefix, pszTypeId );

		writer.Line( "nullptr," );
		writer.Unindent();
		writer.Line( "};" );
		writer.Blank();
	};

	WriteTable( "CSchemaClassInfo", sClassTable.Get(), "ImplSchema_ClassInfo_", classIds );
	WriteTable( "CSchemaEnumInfo", sEnumTable.Get(), "ImplSchema_EnumInfo_", enumIds );
	WriteTable( "SchemaAtomicTypeInfo_t", sAtomicTable.Get(), "ImplSchema_AtomicInfo_", atomicIds );

	writer.Line( "SCHEMAGEN_LOCAL int %s;", sAnchor.Get() );
	writer.Blank();

	// Type table
	writer.Line( "static void ImplSchema_ProjectTypesInit_%s( ISchemaSystem *pSchemaSystem )", pszId );
	writer.Line( "{" );
	writer.Indent();
	writer.Line( "CSchemaSystemTypeScope *pScope = pSchemaSystem->FindOrCreateTypeScopeForModule( GetNameOfModule() );" );
	writer.Line( "CSchemaSystemTypeScope *pDeclScope = %s;", m_bGlobalScope ? "pSchemaSystem->GlobalTypeScope()" : "pScope" );
	writer.Blank();

	for ( int nInput : m_TypesInitInputs )
		writer.Line( "ImplSchema_TypesInit_%s( pScope, pDeclScope, %s );", m_Project.m_Inputs[ nInput ].m_sId.Get(), sTypes.Get() );

	writer.Unindent();
	writer.Line( "}" );
	writer.Blank();

	// Registrar
	writer.Line( "class %s final : public CSchemaRegistration", sRegistration.Get() );
	writer.Line( "{" );
	writer.Line( "public:" );
	writer.Indent();
	writer.Line( "bool RegisterAllBindings( ISchemaSystem *pSchemaSystem, SchemaRegistrationPhase_t ePhase, CBufferString *pFailureReason ) override;" );
	writer.Unindent();
	writer.Blank();
	writer.Line( "private:" );
	writer.Indent();
	writer.Line( "// RegisterAllModuleData retries a phase for every registrar of the module, done phases stay done" );
	writer.Line( "bool m_bPhaseDone[ SCHEMA_REGISTRATION_PHASE_COUNT ] = {};" );
	writer.Unindent();
	writer.Line( "};" );
	writer.Blank();

	writer.Line( "bool %s::RegisterAllBindings( ISchemaSystem *pSchemaSystem, SchemaRegistrationPhase_t ePhase, CBufferString *pFailureReason )", sRegistration.Get() );
	writer.Line( "{" );
	writer.Indent();
	writer.Line( "if ( ePhase < 0 || ePhase >= SCHEMA_REGISTRATION_PHASE_COUNT || m_bPhaseDone[ ePhase ] )" );
	writer.Indent();
	writer.Line( "return true;" );
	writer.Unindent();
	writer.Blank();
	writer.Line( "const char *pszModuleName = GetNameOfModule();" );
	writer.Blank();
	writer.Line( "switch ( ePhase )" );
	writer.Line( "{" );
	writer.Indent();

	writer.Line( "case SCHEMA_REGISTRATION_PHASE_TYPE_TABLES:" );
	writer.Line( "{" );
	writer.Indent();
	writer.Line( "ImplSchema_ProjectTypesInit_%s( pSchemaSystem );", pszId );
	writer.Line( "break;" );
	writer.Unindent();
	writer.Line( "}" );
	writer.Blank();

	writer.Line( "case SCHEMA_REGISTRATION_PHASE_ATOMIC_TYPES_AND_ENUMS:" );
	writer.Line( "{" );
	writer.Indent();
	writer.Line( "pSchemaSystem->RegisterAtomics( pszModuleName, \"%s\", %s, ARRAYSIZE( %s ), %s );", pszProject, sTypes.Get(), sTypes.Get(), sAtomicTable.Get() );
	writer.Line( "pSchemaSystem->RegisterEnums( pszModuleName, \"%s\", %s, ARRAYSIZE( %s ), %s );", pszProject, sTypes.Get(), sTypes.Get(), sEnumTable.Get() );
	writer.Line( "break;" );
	writer.Unindent();
	writer.Line( "}" );
	writer.Blank();

	writer.Line( "case SCHEMA_REGISTRATION_PHASE_CLASSES:" );
	writer.Line( "{" );
	writer.Indent();
	if ( m_ResolveInputs.Count() > 0 )
	{
		writer.Line( "// Types of other modules may register later, a miss is retried" );
		writer.Line( "bool bResolved = true;" );
		writer.Blank();

		for ( int nInput : m_ResolveInputs )
			writer.Line( "bResolved &= ImplSchema_ResolveExternals_%s( pSchemaSystem, pFailureReason );", m_Project.m_Inputs[ nInput ].m_sId.Get() );

		writer.Blank();
		writer.Line( "if ( !bResolved )" );
		writer.Indent();
		writer.Line( "return false;" );
		writer.Unindent();
		writer.Blank();
	}
	writer.Line( "CBufferString sError;" );
	writer.Blank();
	writer.Line( "if ( !pSchemaSystem->RegisterClasses( pszModuleName, \"%s\", %s, ARRAYSIZE( %s ), %s, &sError ) )", pszProject, sTypes.Get(), sTypes.Get(), sClassTable.Get() );
	writer.Indent();
	writer.Line( "Plat_FatalError( \"%%s: schema project \\\"%s\\\" cannot register its classes: %%s\\n\", pszModuleName, sError.Get() );", pszProject );
	writer.Unindent();
	writer.Blank();
	writer.Line( "break;" );
	writer.Unindent();
	writer.Line( "}" );
	writer.Blank();

	writer.Line( "case SCHEMA_REGISTRATION_PHASE_VALIDATION:" );
	writer.Line( "{" );
	writer.Indent();
	writer.Line( "pSchemaSystem->ValidateClasses( %s );", sClassTable.Get() );
	writer.Line( "break;" );
	writer.Unindent();
	writer.Line( "}" );
	writer.Blank();

	writer.Line( "default:" );
	writer.Indent();
	writer.Line( "break;" );
	writer.Unindent();
	writer.Unindent();
	writer.Line( "}" );
	writer.Blank();
	writer.Line( "m_bPhaseDone[ ePhase ] = true;" );
	writer.Line( "++%s;", sAnchor.Get() );
	writer.Blank();
	writer.Line( "return true;" );
	writer.Unindent();
	writer.Line( "}" );
	writer.Blank();

	writer.Line( "SCHEMAGEN_LOCAL %s CSchemaAutoRegistration_%s;", sRegistration.Get(), pszId );
	writer.Blank();

	// A static library with the project needs a reference to keep this unit in the module
	writer.Line( "extern \"C\" SCHEMAGEN_LOCAL int *ImplSchema_Anchor_%s()", pszId );
	writer.Line( "{" );
	writer.Indent();
	writer.Line( "return &%s;", sAnchor.Get() );
	writer.Unindent();
	writer.Line( "}" );

	output.m_sPath = m_Project.m_sRegistration;
}

bool CCodegen::Generate( CUtlLeanVector< CodegenOutput_t * > &outputs )
{
	bool bSuccess = CollectTypes();

	AssignTypeSlots();

	for ( int nInput : m_SortedInputs )
	{
		CodegenOutput_t *pOutput = new CodegenOutput_t;

		bSuccess &= WriteInput( nInput, *pOutput );
		outputs.AddToTail( pOutput );
	}

	CodegenOutput_t *pRegistration = new CodegenOutput_t;

	WriteRegistration( *pRegistration );
	outputs.AddToTail( pRegistration );

	return bSuccess;
}

} // namespace

bool Codegen_Generate( const SchemaProject_t &project, const CUtlLeanVector< const ModelValue_t * > &models, CUtlLeanVector< CodegenOutput_t * > &outputs )
{
	return CCodegen( project, models ).Generate( outputs );
}
