if(NOT PROTOBUF_DIR)
	message(FATAL_ERROR "PROTOBUF_DIR is empty")
endif()

if(NOT SOURCESDK_DIR)
	message(FATAL_ERROR "SOURCESDK_DIR is empty")
endif()

set(SOURCESDK_PROTOC_EXECUTABLE "${DEVTOOLS_BIN_DIR}/${PROTOBUF_PROTOC_NAME}${CMAKE_EXECUTABLE_SUFFIX}")

set(SOURCESDK_PROTOBUF_SOURCE_DIR "${PROTOBUF_DIR}/src")
list(APPEND SOURCESDK_INCLUDE_DIR ${SOURCESDK_PROTOBUF_SOURCE_DIR})

set(SOURCESDK_PROTO_FILENAME_FILES
	${SOURCESDK_PROTO_FILENAME_FILES}
)

foreach(PROTO_FILE IN LISTS SOURCESDK_PROTO_FILES)
	list(APPEND SOURCESDK_PROTO_FILENAME_FILES "${PROTO_FILE}.proto")
endforeach()

set(SOURCESDK_PROTO_SOURCE_FILES
	${SOURCESDK_PROTO_SOURCE_FILES}
)

foreach(PROTO_FILE IN LISTS SOURCESDK_PROTO_FILES)
	list(APPEND SOURCESDK_PROTO_SOURCE_FILES "${PROTO_FILE}.pb.cc")
endforeach()

set(SOURCESDK_LOGS_DIRECTORY "logs")
set(SOURCESDK_LOGS_PROTOS_DIRECTORY "${SOURCESDK_LOGS_DIRECTORY}/protos")
string(TIMESTAMP SOURCESDK_PROTO_DATE_FILENAME "%Y_%m_%d-%H_%M_%S")
set(SOURCESDK_LOGS_PROTOS_DATE_DIRECTORY "${SOURCESDK_LOGS_PROTOS_DIRECTORY}/${SOURCESDK_PROTO_DATE_FILENAME}")
set(SOURCESDK_LOGS_PROTOS_DATE_ERRORS_DIRECTORY "${SOURCESDK_LOGS_PROTOS_DIRECTORY}/${SOURCESDK_PROTO_DATE_FILENAME}/errors")
