if(NOT SOURCESDK_DIR)
	message(FATAL_ERROR "SOURCESDK_DIR is empty")
endif()

set(SOURCESDK_COMMON_INCLUDE_DIR "${SOURCESDK_DIR}/common")

list(APPEND SOURCESDK_INCLUDE_DIRS
	${SOURCESDK_COMMON_INCLUDE_DIR}
)
