if(NOT SOURCESDK_DIR)
	message(FATAL_ERROR "SOURCESDK_DIR is empty")
endif()

set(SOURCESDK_PUBLIC_ENGINE_INCLUDE_DIR "${SOURCESDK_DIR}/public/engine")

list(APPEND SOURCESDK_INCLUDE_DIRS
	${SOURCESDK_PUBLIC_ENGINE_INCLUDE_DIR}
)
