if(NOT SOURCESDK_DIR)
	message(FATAL_ERROR "SOURCESDK_DIR is empty")
endif()

set(SOURCESDK_PUBLIC_ENGINE_INCLUDE_DIR "${SOURCESDK_PUBLIC_DIR}/engine")

list(APPEND SOURCESDK_INCLUDE_DIRS
	${SOURCESDK_PUBLIC_ENGINE_INCLUDE_DIR}
)

# Headers with schema types, the input of the sourcesdk_schema check target
list(APPEND SOURCESDK_SCHEMA_SOURCE_FILES
	${SOURCESDK_PUBLIC_ENGINE_INCLUDE_DIR}/IEngineService.h
)
