if(NOT SOURCESDK_DIR)
	message(FATAL_ERROR "SOURCESDK_DIR is empty")
endif()

if(NOT SOURCESDK_ENTITY2_DIR)
	message(FATAL_ERROR "SOURCESDK_ENTITY2_DIR is empty")
endif()

set(SOURCESDK_ENTITY2_NAME "entity2")
set(SOURCESDK_ENTITY2_OUTPUT_NAME "${SOURCESDK_ENTITY2_NAME}")

set(SOURCESDK_ENTITY2_COMPILER_OPTIONS
	${SOURCESDK_COMPILER_OPTIONS}
)

set(SOURCESDK_ENTITY2_LINKER_OPTIONS
	${SOURCESDK_LINKER_OPTIONS}
)

set(SOURCESDK_ENTITY2_COMPILE_DEFINTIONS
	${SOURCESDK_COMPILE_DEFINTIONS}

	-D_LIB
)

set(SOURCESDK_ENTITY2_INCLUDE_DIR
	${SOURCESDK_DIR}/common
	${SOURCESDK_PROTOBUF_SOURCE_DIR}

	${SOURCESDK_DIR}/game/shared
	${SOURCESDK_DIR}/public/entity2
	${SOURCESDK_DIR}/public/mathlib
	${SOURCESDK_DIR}/public/tier0
	${SOURCESDK_DIR}/public/tier1
	${SOURCESDK_DIR}/public
)

set(SOURCESDK_ENTITY2_SOURCE_FILES
	${SOURCESDK_ENTITY2_DIR}/entityidentity.cpp
	${SOURCESDK_ENTITY2_DIR}/entitysystem.cpp
	${SOURCESDK_ENTITY2_DIR}/entitykeyvalues.cpp
)

add_library(${SOURCESDK_ENTITY2_NAME} ${SOURCESDK_ENTITY2_SOURCE_FILES})

set_target_properties(${SOURCESDK_ENTITY2_NAME} PROPERTIES
	CXX_STANDARD 17
	CXX_STANDARD_REQUIRED ON
	CXX_EXTENSIONS OFF

	C_STANDARD 17
	C_STANDARD_REQUIRED ON
	C_EXTENSIONS OFF
)

set_target_properties(${SOURCESDK_ENTITY2_NAME} PROPERTIES OUTPUT_NAME ${SOURCESDK_ENTITY2_OUTPUT_NAME})

if(WINDOWS)
	set_target_properties(${SOURCESDK_ENTITY2_NAME} PROPERTIES MSVC_RUNTIME_LIBRARY "MultiThreaded$<$<CONFIG:Debug>:Debug>")
endif()

target_compile_options(${SOURCESDK_ENTITY2_NAME} PRIVATE ${PLATFORM_COMPILER_OPTIONS} ${SOURCESDK_ENTITY2_COMPILER_OPTIONS})
target_link_options(${SOURCESDK_ENTITY2_NAME} PRIVATE ${PLATFORM_LINKER_OPTIONS} ${SOURCESDK_ENTITY2_LINKER_OPTIONS})

target_compile_definitions(${SOURCESDK_ENTITY2_NAME} PRIVATE ${PLATFORM_COMPILE_DEFINITIONS} ${SOURCESDK_ENTITY2_COMPILE_DEFINTIONS})
target_include_directories(${SOURCESDK_ENTITY2_NAME} PRIVATE ${PLATFORM_INCLUDE_DIR} ${SOURCESDK_ENTITY2_INCLUDE_DIR})
