if(NOT SOURCESDK_DIR)
	message(FATAL_ERROR "SOURCESDK_DIR is empty")
endif()

if(NOT SOURCESDK_INTERFACES_DIR)
	message(FATAL_ERROR "SOURCESDK_INTERFACES_DIR is empty")
endif()

set(SOURCESDK_INTERFACES_NAME "interfaces")
set(SOURCESDK_INTERFACES_OUTPUT_NAME "${SOURCESDK_INTERFACES_NAME}")

set(SOURCESDK_INTERFACES_COMPILER_OPTIONS
	${SOURCESDK_COMPILER_OPTIONS}
)

set(SOURCESDK_INTERFACES_LINKER_OPTIONS
	${SOURCESDK_LINKER_OPTIONS}
)

set(SOURCESDK_INTERFACES_COMPILE_DEFINTIONS
	${SOURCESDK_COMPILE_DEFINTIONS}

	-D_LIB
)

set(SOURCESDK_INTERFACES_INCLUDE_DIR
	${SOURCESDK_DIR}/public/tier0
	${SOURCESDK_DIR}/public/tier1
	${SOURCESDK_DIR}/public
)

set(SOURCESDK_INTERFACES_SOURCE_FILES
	${SOURCESDK_INTERFACES_DIR}/interfaces.cpp
)

add_library(${SOURCESDK_INTERFACES_NAME} ${SOURCESDK_INTERFACES_SOURCE_FILES})

set_property(TARGET ${SOURCESDK_INTERFACES_NAME} PROPERTY C_STANDARD 17)
set_property(TARGET ${SOURCESDK_INTERFACES_NAME} PROPERTY C_STANDARD_REQUIRED ON)
set_property(TARGET ${SOURCESDK_INTERFACES_NAME} PROPERTY C_EXTENSIONS OFF)

set_property(TARGET ${SOURCESDK_INTERFACES_NAME} PROPERTY CXX_STANDARD 17)
set_property(TARGET ${SOURCESDK_INTERFACES_NAME} PROPERTY CXX_STANDARD_REQUIRED ON)
set_property(TARGET ${SOURCESDK_INTERFACES_NAME} PROPERTY CXX_EXTENSIONS OFF)

set_target_properties(${SOURCESDK_INTERFACES_NAME} PROPERTIES OUTPUT_NAME ${SOURCESDK_INTERFACES_OUTPUT_NAME})

target_compile_options(${SOURCESDK_INTERFACES_NAME} PRIVATE ${PLATFORM_COMPILER_OPTIONS} ${SOURCESDK_INTERFACES_COMPILER_OPTIONS})
target_link_options(${SOURCESDK_INTERFACES_NAME} PRIVATE ${PLATFORM_LINKER_OPTIONS} ${SOURCESDK_INTERFACES_LINKER_OPTIONS})

target_compile_definitions(${SOURCESDK_INTERFACES_NAME} PRIVATE ${PLATFORM_COMPILE_DEFINITIONS} ${SOURCESDK_INTERFACES_COMPILE_DEFINTIONS})
target_include_directories(${SOURCESDK_INTERFACES_NAME} PRIVATE ${PLATFORM_INCLUDE_DIR} ${SOURCESDK_INTERFACES_INCLUDE_DIR})
