if(NOT SOURCESDK_DIR)
	message(FATAL_ERROR "SOURCESDK_DIR is empty")
endif()

if(NOT SOURCESDK_INTERFACES_DIR)
	message(FATAL_ERROR "SOURCESDK_INTERFACES_DIR is empty")
endif()

set(SOURCESDK_INTERFACES_NAME "interfaces")
set(SOURCESDK_INTERFACES_OUTPUT_NAME "${SOURCESDK_INTERFACES_NAME}")

set(SOURCESDK_INTERFACES_COMPILER_OPTIONS
	${SOURCESDK_COMPILER_OPTIONS}
)

set(SOURCESDK_INTERFACES_LINK_OPTIONS
	${SOURCESDK_LINK_OPTIONS}
)

set(SOURCESDK_INTERFACES_COMPILE_DEFINTIONS
	${SOURCESDK_COMPILE_DEFINTIONS}

	_LIB
)

set(SOURCESDK_PUBLIC_INTERFACES_INCLUDE_DIR "${SOURCESDK_DIR}/interfaces")

set(SOURCESDK_INTERFACES_INCLUDE_DIRS
	${SOURCESDK_PUBLIC_INTERFACES_INCLUDE_DIR}
	${SOURCESDK_DIR}/public/tier0
	${SOURCESDK_DIR}/public/tier1
	${SOURCESDK_DIR}/public
)

list(APPEND SOURCESDK_INCLUDE_DIRS
	${SOURCESDK_PUBLIC_INTERFACES_INCLUDE_DIR}
)

set(SOURCESDK_INTERFACES_SOURCE_FILES
	${SOURCESDK_INTERFACES_DIR}/interfaces.cpp
)

add_library(${SOURCESDK_INTERFACES_NAME} ${SOURCESDK_INTERFACES_SOURCE_FILES})

set_target_properties(${SOURCESDK_INTERFACES_NAME} PROPERTIES
	C_STANDARD 17
	C_STANDARD_REQUIRED ON
	C_EXTENSIONS OFF

	CXX_STANDARD 17
	CXX_STANDARD_REQUIRED ON
	CXX_EXTENSIONS OFF
)

set_target_properties(${SOURCESDK_INTERFACES_NAME} PROPERTIES OUTPUT_NAME ${SOURCESDK_INTERFACES_OUTPUT_NAME})

if(WINDOWS)
	set_target_properties(${SOURCESDK_INTERFACES_NAME} PROPERTIES MSVC_RUNTIME_LIBRARY "MultiThreaded$<$<CONFIG:Debug>:Debug>")
elseif(MACOS)
	set_target_properties(${SOURCESDK_INTERFACES_NAME} PROPERTIES OSX_ARCHITECTURES "x86_64")
endif()

target_compile_options(${SOURCESDK_INTERFACES_NAME} PRIVATE ${PLATFORM_COMPILER_OPTIONS} ${SOURCESDK_INTERFACES_COMPILER_OPTIONS})
target_link_options(${SOURCESDK_INTERFACES_NAME} PRIVATE ${PLATFORM_LINK_OPTIONS} ${SOURCESDK_INTERFACES_LINK_OPTIONS})

target_compile_definitions(${SOURCESDK_INTERFACES_NAME} PRIVATE ${PLATFORM_COMPILE_DEFINITIONS} ${SOURCESDK_INTERFACES_COMPILE_DEFINTIONS})
target_include_directories(${SOURCESDK_INTERFACES_NAME} PRIVATE ${PLATFORM_INCLUDE_DIRS} ${SOURCESDK_INTERFACES_INCLUDE_DIRS})
