if(NOT SOURCESDK_DIR)
	message(FATAL_ERROR "SOURCESDK_DIR is empty")
endif()

if(NOT SOURCESDK_KV3LIB_DIR)
	message(FATAL_ERROR "SOURCESDK_KV3LIB_DIR is empty")
endif()

set(SOURCESDK_KV3LIB_NAME "kv3lib")
set(SOURCESDK_KV3LIB_OUTPUT_NAME "${SOURCESDK_KV3LIB_NAME}")

set(SOURCESDK_KV3LIB_COMPILER_OPTIONS
	${SOURCESDK_COMPILER_OPTIONS}
)

set(SOURCESDK_KV3LIB_LINK_OPTIONS
	${SOURCESDK_LINK_OPTIONS}
)

set(SOURCESDK_KV3LIB_COMPILE_DEFINITIONS
	${SOURCESDK_COMPILE_DEFINITIONS}

	_LIB
)

set(SOURCESDK_PUBLIC_KV3LIB_INCLUDE_DIR "${SOURCESDK_PUBLIC_DIR}/kv3lib")

set(SOURCESDK_KV3LIB_INCLUDE_DIRS
	${SOURCESDK_PUBLIC_KV3LIB_INCLUDE_DIR}
	${SOURCESDK_PUBLIC_DIR}/tier0
	${SOURCESDK_PUBLIC_DIR}/tier1
	${SOURCESDK_PUBLIC_DIR}
)

list(APPEND SOURCESDK_INCLUDE_DIRS
	${SOURCESDK_PUBLIC_KV3LIB_INCLUDE_DIR}
)

# Headers with schema types, the input of the sourcesdk_schema check target
list(APPEND SOURCESDK_SCHEMA_SOURCE_FILES
	${SOURCESDK_PUBLIC_KV3LIB_INCLUDE_DIR}/keyvalues3.h
)

set(SOURCESDK_KV3LIB_SOURCE_FILES
	${SOURCESDK_KV3LIB_DIR}/keyvalues3.cpp
	${SOURCESDK_KV3LIB_DIR}/kv3text.cpp
	${SOURCESDK_KV3LIB_DIR}/kv3transfer.cpp
	${SOURCESDK_KV3LIB_DIR}/kv3transfer_schema.cpp
)

add_library(${SOURCESDK_KV3LIB_NAME} STATIC ${SOURCESDK_KV3LIB_SOURCE_FILES})
add_library(${PROJECT_NAME}::${SOURCESDK_KV3LIB_NAME} ALIAS ${SOURCESDK_KV3LIB_NAME})

set_target_properties(${SOURCESDK_KV3LIB_NAME} PROPERTIES
	C_STANDARD 17
	C_STANDARD_REQUIRED ON
	C_EXTENSIONS OFF

	CXX_STANDARD 17
	CXX_STANDARD_REQUIRED ON
	CXX_EXTENSIONS OFF
)

set_target_properties(${SOURCESDK_KV3LIB_NAME} PROPERTIES OUTPUT_NAME ${SOURCESDK_KV3LIB_OUTPUT_NAME})

if(WINDOWS)
	if(SOURCESDK_MSVC_RUNTIME_LIBRARY)
		set_target_properties(${SOURCESDK_KV3LIB_NAME} PROPERTIES MSVC_RUNTIME_LIBRARY "MultiThreaded$<$<CONFIG:Debug>:Debug>")
	endif()
elseif(MACOS)
	set_target_properties(${SOURCESDK_KV3LIB_NAME} PROPERTIES OSX_ARCHITECTURES "x86_64")
endif()

target_compile_options(${SOURCESDK_KV3LIB_NAME} PUBLIC ${PLATFORM_COMPILE_OPTIONS} ${SOURCESDK_KV3LIB_COMPILER_OPTIONS})
target_link_options(${SOURCESDK_KV3LIB_NAME} PUBLIC ${PLATFORM_LINK_OPTIONS} ${SOURCESDK_KV3LIB_LINK_OPTIONS})

target_compile_definitions(${SOURCESDK_KV3LIB_NAME} PUBLIC ${PLATFORM_COMPILE_DEFINITIONS} ${SOURCESDK_KV3LIB_COMPILE_DEFINITIONS})
target_include_directories(${SOURCESDK_KV3LIB_NAME} PUBLIC ${PLATFORM_INCLUDE_DIRS} ${SOURCESDK_KV3LIB_INCLUDE_DIRS})
target_link_libraries(${SOURCESDK_KV3LIB_NAME} PUBLIC ${SOURCESDK_TIER1_NAME})
