if(NOT SOURCESDK_DIR)
	message(FATAL_ERROR "SOURCESDK_DIR is empty")
endif()

if(NOT SOURCESDK_MATHLIB_DIR)
	message(FATAL_ERROR "SOURCESDK_MATHLIB_DIR is empty")
endif()

set(SOURCESDK_MATHLIB_NAME "mathlib")
set(SOURCESDK_MATHLIB_OUTPUT_NAME "math")

set(SOURCESDK_MATHLIB_COMPILER_OPTIONS
	${SOURCESDK_COMPILER_OPTIONS}
)

set(SOURCESDK_MATHLIB_LINK_OPTIONS
	${SOURCESDK_LINK_OPTIONS}
)

set(SOURCESDK_MATHLIB_COMPILE_DEFINTIONS
	${SOURCESDK_COMPILE_DEFINTIONS}

	_LIB
)

set(SOURCESDK_MATHLIB_INCLUDE_DIRS
	${SOURCESDK_DIR}/public/mathlib
	${SOURCESDK_DIR}/public/tier0
	${SOURCESDK_DIR}/public/tier1
	${SOURCESDK_DIR}/public
)

set(SOURCESDK_MATHLIB_SOURCE_FILES
	${SOURCESDK_MATHLIB_DIR}/anorms.cpp
	${SOURCESDK_MATHLIB_DIR}/bumpvects.cpp
	${SOURCESDK_MATHLIB_DIR}/color_conversion.cpp
	${SOURCESDK_MATHLIB_DIR}/halton.cpp
	${SOURCESDK_MATHLIB_DIR}/IceKey.cpp
	${SOURCESDK_MATHLIB_DIR}/imagequant.cpp
	${SOURCESDK_MATHLIB_DIR}/lightdesc.cpp
	${SOURCESDK_MATHLIB_DIR}/mathlib_base.cpp
	${SOURCESDK_MATHLIB_DIR}/polyhedron.cpp
	${SOURCESDK_MATHLIB_DIR}/powsse.cpp
	${SOURCESDK_MATHLIB_DIR}/quantize.cpp
	${SOURCESDK_MATHLIB_DIR}/randsse.cpp
	${SOURCESDK_MATHLIB_DIR}/simdvectormatrix.cpp
	${SOURCESDK_MATHLIB_DIR}/sparse_convolution_noise.cpp
	${SOURCESDK_MATHLIB_DIR}/sse.cpp
	${SOURCESDK_MATHLIB_DIR}/sseconst.cpp
	${SOURCESDK_MATHLIB_DIR}/ssenoise.cpp
	${SOURCESDK_MATHLIB_DIR}/vector.cpp
	${SOURCESDK_MATHLIB_DIR}/vmatrix.cpp
)

add_library(${SOURCESDK_MATHLIB_NAME} ${SOURCESDK_MATHLIB_SOURCE_FILES})

set_target_properties(${SOURCESDK_MATHLIB_NAME} PROPERTIES
	C_STANDARD 17
	C_STANDARD_REQUIRED ON
	C_EXTENSIONS OFF

	CXX_STANDARD 17
	CXX_STANDARD_REQUIRED ON
	CXX_EXTENSIONS OFF
)

set_target_properties(${SOURCESDK_MATHLIB_NAME} PROPERTIES OUTPUT_NAME ${SOURCESDK_MATHLIB_OUTPUT_NAME})

if(WINDOWS)
	set_target_properties(${SOURCESDK_MATHLIB_NAME} PROPERTIES MSVC_RUNTIME_LIBRARY "MultiThreaded$<$<CONFIG:Debug>:Debug>")
endif()

target_compile_options(${SOURCESDK_MATHLIB_NAME} PRIVATE ${PLATFORM_COMPILER_OPTIONS} ${SOURCESDK_MATHLIB_COMPILER_OPTIONS})
target_link_options(${SOURCESDK_MATHLIB_NAME} PRIVATE ${PLATFORM_LINK_OPTIONS} ${SOURCESDK_MATHLIB_LINK_OPTIONS})

target_compile_definitions(${SOURCESDK_MATHLIB_NAME} PRIVATE ${PLATFORM_COMPILE_DEFINITIONS} ${SOURCESDK_MATHLIB_COMPILE_DEFINTIONS})
target_include_directories(${SOURCESDK_MATHLIB_NAME} PRIVATE ${PLATFORM_INCLUDE_DIRS} ${SOURCESDK_MATHLIB_INCLUDE_DIRS})
