if(NOT SOURCESDK_DIR)
	message(FATAL_ERROR "SOURCESDK_DIR is empty")
endif()

if(NOT SOURCESDK_LINK_TIER0)
	message(FATAL_ERROR "SOURCESDK_SCHEMACOMPILER needs SOURCESDK_LINK_TIER0")
endif()

set(SOURCESDK_SCHEMACOMPILER_NAME "schemacompiler")
set(SOURCESDK_SCHEMACOMPILER_SDK_NAME "${SOURCESDK_SCHEMACOMPILER_NAME}_sdk")
set(SOURCESDK_SCHEMACOMPILER_DIR "${SOURCESDK_DIR}/utils/${SOURCESDK_SCHEMACOMPILER_NAME}")

find_package(Clang CONFIG)

if(NOT Clang_FOUND)
	message(FATAL_ERROR "${SOURCESDK_SCHEMACOMPILER_NAME} needs Clang/LLVM 17 or newer development files; set Clang_DIR and LLVM_DIR to their lib/cmake/clang and lib/cmake/llvm or turn SOURCESDK_SCHEMACOMPILER off")
endif()

if(LLVM_PACKAGE_VERSION VERSION_LESS 17)
	message(FATAL_ERROR "${SOURCESDK_SCHEMACOMPILER_NAME} needs LLVM 17 or newer, found ${LLVM_PACKAGE_VERSION} at \"${LLVM_DIR}\"")
endif()

message(STATUS "${SOURCESDK_SCHEMACOMPILER_NAME}: LLVM ${LLVM_PACKAGE_VERSION} from \"${LLVM_DIR}\"")

# Builtin headers (stddef.h, xmmintrin.h) of the Clang the tool links
set(SOURCESDK_SCHEMACOMPILER_CLANG_RESOURCE_DIR "${LLVM_LIBRARY_DIR}/clang/${LLVM_VERSION_MAJOR}")

if(NOT EXISTS "${SOURCESDK_SCHEMACOMPILER_CLANG_RESOURCE_DIR}/include/stddef.h")
	message(FATAL_ERROR "Clang builtin headers are missing in \"${SOURCESDK_SCHEMACOMPILER_CLANG_RESOURCE_DIR}/include\"")
endif()

#
# Host copy of kv3lib and tier1. The SDK lists are not reused: _GLIBCXX_USE_CXX11_ABI=0 breaks the LLVM
# libraries and -fno-threadsafe-statics the parser threads
#
set(SOURCESDK_SCHEMACOMPILER_SDK_SOURCE_FILES
	${SOURCESDK_KV3LIB_DIR}/keyvalues3.cpp
	${SOURCESDK_KV3LIB_DIR}/kv3text.cpp
	${SOURCESDK_TIER1_DIR}/bitbuf.cpp
	${SOURCESDK_TIER1_DIR}/convar.cpp
	${SOURCESDK_TIER1_DIR}/generichash.cpp
	${SOURCESDK_TIER1_DIR}/newbitbuf.cpp
	${SOURCESDK_TIER1_DIR}/processor_detect.cpp
	${SOURCESDK_TIER1_DIR}/rangecheckedvar.cpp
	${SOURCESDK_TIER1_DIR}/tier1.cpp
	${SOURCESDK_TIER1_DIR}/utlbufferutil.cpp
)

set(SOURCESDK_SCHEMACOMPILER_SDK_INCLUDE_DIRS
	${SOURCESDK_PUBLIC_DIR}
	${SOURCESDK_PUBLIC_DIR}/tier0
	${SOURCESDK_PUBLIC_DIR}/tier1
	${SOURCESDK_PUBLIC_DIR}/kv3lib
	${SOURCESDK_PUBLIC_DIR}/mathlib
	${SOURCESDK_COMMON_DIR}
)

set(SOURCESDK_SCHEMACOMPILER_SDK_COMPILE_DEFINITIONS
	PLATFORM_64BITS X64BITS
	TIER1_STATIC_LIB _LIB
	NDEBUG
)

if(WINDOWS)
	set(SOURCESDK_SCHEMACOMPILER_SDK_COMPILE_DEFINITIONS
		${SOURCESDK_SCHEMACOMPILER_SDK_COMPILE_DEFINITIONS}

		_WIN32 WIN32 _WINDOWS
		COMPILER_MSVC COMPILER_MSVC64
		_ALLOW_KEYWORD_MACROS __STDC_LIMIT_MACROS
		_CRT_SECURE_NO_WARNINGS=1 _CRT_SECURE_NO_DEPRECATE=1 _CRT_NONSTDC_NO_DEPRECATE=1
	)
elseif(LINUX)
	set(SOURCESDK_SCHEMACOMPILER_SDK_COMPILE_DEFINITIONS
		${SOURCESDK_SCHEMACOMPILER_SDK_COMPILE_DEFINITIONS}

		POSIX _LINUX LINUX
		bswap_16=__bswap_16 bswap_32=__bswap_32 bswap_64=__bswap_64
	)
elseif(MACOS)
	set(SOURCESDK_SCHEMACOMPILER_SDK_COMPILE_DEFINITIONS
		${SOURCESDK_SCHEMACOMPILER_SDK_COMPILE_DEFINITIONS}

		POSIX OSX _OSX
	)
endif()

# Optimized in every configuration, the generator runs on each build
if(WINDOWS)
	set(SOURCESDK_SCHEMACOMPILER_COMPILE_OPTIONS
		/wd4005 /wd4819 /wd4828 /wd5033 /wd4245 /wd4018
		/permissive- /utf-8 /arch:SSE4.2
	)

	# The LLVM libraries are release builds
	set(SOURCESDK_SCHEMACOMPILER_COMPILE_DEFINITIONS
		_ITERATOR_DEBUG_LEVEL=0
	)
else()
	set(SOURCESDK_SCHEMACOMPILER_COMPILE_OPTIONS
		-Wno-attributes -Wno-ignored-attributes -Wno-invalid-offsetof
		-msse4.2 -fPIC -fno-strict-aliasing
		-O2
	)

	set(SOURCESDK_SCHEMACOMPILER_COMPILE_DEFINITIONS)
endif()

add_library(${SOURCESDK_SCHEMACOMPILER_SDK_NAME} STATIC ${SOURCESDK_SCHEMACOMPILER_SDK_SOURCE_FILES})

set_target_properties(${SOURCESDK_SCHEMACOMPILER_SDK_NAME} PROPERTIES
	CXX_STANDARD 17
	CXX_STANDARD_REQUIRED ON
	CXX_EXTENSIONS OFF
)

target_compile_definitions(${SOURCESDK_SCHEMACOMPILER_SDK_NAME} PRIVATE ${SOURCESDK_SCHEMACOMPILER_SDK_COMPILE_DEFINITIONS} ${SOURCESDK_SCHEMACOMPILER_COMPILE_DEFINITIONS})
target_compile_options(${SOURCESDK_SCHEMACOMPILER_SDK_NAME} PRIVATE ${SOURCESDK_SCHEMACOMPILER_COMPILE_OPTIONS})
target_include_directories(${SOURCESDK_SCHEMACOMPILER_SDK_NAME} PRIVATE ${SOURCESDK_SCHEMACOMPILER_SDK_INCLUDE_DIRS})
target_link_libraries(${SOURCESDK_SCHEMACOMPILER_SDK_NAME} PUBLIC ${SOURCESDK_TIER0_NAME})

#
# The generator, with the same SDK platform macros; frontend.cpp hides POSIX from the Clang headers
#
set(SOURCESDK_SCHEMACOMPILER_SOURCE_FILES
	${SOURCESDK_SCHEMACOMPILER_DIR}/codegen.cpp
	${SOURCESDK_SCHEMACOMPILER_DIR}/frontend.cpp
	${SOURCESDK_SCHEMACOMPILER_DIR}/main.cpp
	${SOURCESDK_SCHEMACOMPILER_DIR}/model.cpp
	${SOURCESDK_SCHEMACOMPILER_DIR}/project.cpp
	${SOURCESDK_SCHEMACOMPILER_DIR}/script.cpp
	${SOURCESDK_SCHEMACOMPILER_DIR}/utils.cpp
)

set(SOURCESDK_SCHEMACOMPILER_HEADER_FILES
	${SOURCESDK_SCHEMACOMPILER_DIR}/codegen.h
	${SOURCESDK_SCHEMACOMPILER_DIR}/frontend.h
	${SOURCESDK_SCHEMACOMPILER_DIR}/model.h
	${SOURCESDK_SCHEMACOMPILER_DIR}/schemacompiler.h
	${SOURCESDK_SCHEMACOMPILER_DIR}/script.h
)

# GNU ld writes its --dependency-file without escaping spaces: tier0 under such a path relinks every build
if(SOURCESDK_DIR MATCHES " ")
	set(CMAKE_LINK_DEPENDS_USE_LINKER OFF)
endif()

add_executable(${SOURCESDK_SCHEMACOMPILER_NAME} ${SOURCESDK_SCHEMACOMPILER_SOURCE_FILES} ${SOURCESDK_SCHEMACOMPILER_HEADER_FILES})
add_executable(${PROJECT_NAME}::${SOURCESDK_SCHEMACOMPILER_NAME} ALIAS ${SOURCESDK_SCHEMACOMPILER_NAME})

set_target_properties(${SOURCESDK_SCHEMACOMPILER_NAME} PROPERTIES
	CXX_STANDARD 17
	CXX_STANDARD_REQUIRED ON
	CXX_EXTENSIONS OFF
)

if(WINDOWS)
	set_target_properties(${SOURCESDK_SCHEMACOMPILER_NAME} ${SOURCESDK_SCHEMACOMPILER_SDK_NAME} PROPERTIES MSVC_RUNTIME_LIBRARY "MultiThreaded")
elseif(LINUX)
	set_target_properties(${SOURCESDK_SCHEMACOMPILER_NAME} PROPERTIES BUILD_RPATH "\$ORIGIN")
elseif(MACOS)
	set_target_properties(${SOURCESDK_SCHEMACOMPILER_NAME} PROPERTIES BUILD_RPATH "@loader_path")
endif()

separate_arguments(SOURCESDK_SCHEMACOMPILER_LLVM_DEFINITIONS NATIVE_COMMAND "${LLVM_DEFINITIONS}")

target_compile_definitions(${SOURCESDK_SCHEMACOMPILER_NAME} PRIVATE
	${SOURCESDK_SCHEMACOMPILER_SDK_COMPILE_DEFINITIONS}
	${SOURCESDK_SCHEMACOMPILER_COMPILE_DEFINITIONS}

	SCHEMACOMPILER_CLANG_RESOURCE_DIR="${SOURCESDK_SCHEMACOMPILER_CLANG_RESOURCE_DIR}"
)

target_compile_options(${SOURCESDK_SCHEMACOMPILER_NAME} PRIVATE ${SOURCESDK_SCHEMACOMPILER_COMPILE_OPTIONS})
target_include_directories(${SOURCESDK_SCHEMACOMPILER_NAME} PRIVATE ${SOURCESDK_SCHEMACOMPILER_SDK_INCLUDE_DIRS})

set_source_files_properties(${SOURCESDK_SCHEMACOMPILER_DIR}/frontend.cpp PROPERTIES
	INCLUDE_DIRECTORIES "${LLVM_INCLUDE_DIRS};${CLANG_INCLUDE_DIRS}"
	COMPILE_OPTIONS "${SOURCESDK_SCHEMACOMPILER_LLVM_DEFINITIONS};$<$<NOT:$<BOOL:${LLVM_ENABLE_RTTI}>>:$<IF:$<CXX_COMPILER_ID:MSVC>,/GR-,-fno-rtti>>"
)

target_link_libraries(${SOURCESDK_SCHEMACOMPILER_NAME} PRIVATE
	clangTooling
	clangFrontend
	clangSerialization
	clangDriver
	clangParse
	clangSema
	clangAST
	clangLex
	clangBasic
	${SOURCESDK_SCHEMACOMPILER_SDK_NAME}
)

include(CheckIPOSupported)
check_ipo_supported(RESULT SOURCESDK_SCHEMACOMPILER_IPO_SUPPORTED LANGUAGES CXX)

if(SOURCESDK_SCHEMACOMPILER_IPO_SUPPORTED)
	set_target_properties(${SOURCESDK_SCHEMACOMPILER_NAME} ${SOURCESDK_SCHEMACOMPILER_SDK_NAME} PROPERTIES INTERPROCEDURAL_OPTIMIZATION_RELEASE ON)
endif()

# tier0 and the Clang builtin headers next to the executable keep it relocatable
add_custom_command(
	TARGET ${SOURCESDK_SCHEMACOMPILER_NAME}
	POST_BUILD
	COMMAND ${CMAKE_COMMAND} -E copy_if_different $<TARGET_FILE:${SOURCESDK_TIER0_NAME}> $<TARGET_FILE_DIR:${SOURCESDK_SCHEMACOMPILER_NAME}>
	COMMAND ${CMAKE_COMMAND} -E copy_directory "${SOURCESDK_SCHEMACOMPILER_CLANG_RESOURCE_DIR}/include" "$<TARGET_FILE_DIR:${SOURCESDK_SCHEMACOMPILER_NAME}>/clang/include"
	VERBATIM
)
