if(NOT SOURCESDK_DIR)
	message(FATAL_ERROR "SOURCESDK_DIR is empty")
endif()

set(SOURCESDK_STEAM_NAME "steam")
set(SOURCESDK_PUBLIC_STEAM_INCLUDE_DIR "${SOURCESDK_PUBLIC_DIR}/${SOURCESDK_STEAM_NAME}")

list(APPEND SOURCESDK_INCLUDE_DIRS
	${SOURCESDK_PUBLIC_STEAM_INCLUDE_DIR}
)

set(SOURCESDK_STEAMAPI_LIB_FILENAME)
set(SOURCESDK_STEAMAPI_IMPLIB_FILENAME)

if(SOURCESDK_LINK_STEAMWORKS)
	append_sourcesdk_shared_library(SOURCESDK_LINK_LIBRARIES steam_api SOURCESDK_STEAMAPI_LIB_FILENAME SOURCESDK_STEAMAPI_IMPLIB_FILENAME)

	add_library(${SOURCESDK_STEAM_NAME} SHARED IMPORTED)
	add_library(${PROJECT_NAME}::${SOURCESDK_STEAM_NAME} ALIAS ${SOURCESDK_STEAM_NAME})

	if(WINDOWS)
		set_target_properties(${SOURCESDK_STEAM_NAME} PROPERTIES
			IMPORTED_LOCATION_RELEASE "${SOURCESDK_STEAMAPI_LIB_FILENAME}"
			IMPORTED_IMPLIB_RELEASE "${SOURCESDK_STEAMAPI_IMPLIB_FILENAME}"
			INTERFACE_INCLUDE_DIRECTORIES "${SOURCESDK_PUBLIC_STEAM_INCLUDE_DIR}"
		)
	else()
		set_target_properties(${SOURCESDK_STEAM_NAME} PROPERTIES
			IMPORTED_LOCATION_RELEASE "${SOURCESDK_STEAMAPI_LIB_FILENAME}"
			INTERFACE_INCLUDE_DIRECTORIES "${SOURCESDK_PUBLIC_STEAM_INCLUDE_DIR}"
		)
	endif()
endif()
