if(NOT SOURCESDK_DIR)
	message(FATAL_ERROR "SOURCESDK_DIR is empty")
endif()

set(SOURCESDK_STEAM_NAME "steam_api")
set(SOURCESDK_PUBLIC_STEAM_INCLUDE_DIR "${SOURCESDK_PUBLIC_DIR}/steam")

list(APPEND SOURCESDK_INCLUDE_DIRS
	${SOURCESDK_PUBLIC_STEAM_INCLUDE_DIR}
)

set(SOURCESDK_STEAMAPI_LIB_FILENAME)
set(SOURCESDK_STEAMAPI_IMPLIB_FILENAME)

if(SOURCESDK_LINK_STEAMWORKS)
	append_sourcesdk_shared_library(${SOURCESDK_STEAM_NAME} SOURCESDK_STEAMAPI_LIB_FILENAME SOURCESDK_STEAMAPI_IMPLIB_FILENAME)

	add_library(${SOURCESDK_STEAM_NAME} SHARED IMPORTED)
	add_library(${PROJECT_NAME}::${SOURCESDK_STEAM_NAME} ALIAS ${SOURCESDK_STEAM_NAME})

	if(WINDOWS)
		set_target_properties(${SOURCESDK_STEAM_NAME} PROPERTIES
			IMPORTED_LOCATION "${SOURCESDK_STEAMAPI_LIB_FILENAME}"
			IMPORTED_IMPLIB "${SOURCESDK_STEAMAPI_IMPLIB_FILENAME}"
		)
	else()
		set_target_properties(${SOURCESDK_STEAM_NAME} PROPERTIES
			IMPORTED_LOCATION "${SOURCESDK_STEAMAPI_LIB_FILENAME}"
		)
	endif()
endif()
