if(NOT SOURCESDK_DIR)
	message(FATAL_ERROR "SOURCESDK_DIR is empty")
endif()

set(SOURCESDK_PUBLIC_TIER0_INCLUDE_DIR "${SOURCESDK_PUBLIC_DIR}/tier0")

list(APPEND SOURCESDK_INCLUDE_DIRS
	${SOURCESDK_PUBLIC_TIER0_INCLUDE_DIR}
)

if(SOURCESDK_LINK_TIER0)
	append_sourcesdk_shared_library(SOURCESDK_LINK_LIBRARIES tier0)
endif()
