if(NOT SOURCESDK_DIR)
	message(FATAL_ERROR "SOURCESDK_DIR is empty")
endif()

set(SOURCESDK_TIER0_NAME "tier0")
set(SOURCESDK_PUBLIC_TIER0_INCLUDE_DIR "${SOURCESDK_PUBLIC_DIR}/${SOURCESDK_TIER0_NAME}")

list(APPEND SOURCESDK_INCLUDE_DIRS
	${SOURCESDK_PUBLIC_TIER0_INCLUDE_DIR}
)

set(SOURCESDK_TIER0_LIB_FILENAME)
set(SOURCESDK_TIER0_IMPLIB_FILENAME)

if(SOURCESDK_LINK_TIER0)
	append_sourcesdk_shared_library(${SOURCESDK_TIER0_NAME} SOURCESDK_TIER0_LIB_FILENAME SOURCESDK_TIER0_IMPLIB_FILENAME)

	add_library(${SOURCESDK_TIER0_NAME} SHARED IMPORTED)
	add_library(${PROJECT_NAME}::${SOURCESDK_TIER0_NAME} ALIAS ${SOURCESDK_TIER0_NAME})

	if(WINDOWS)
		set_target_properties(${SOURCESDK_TIER0_NAME} PROPERTIES
			IMPORTED_LOCATION "${SOURCESDK_TIER0_LIB_FILENAME}"
			IMPORTED_IMPLIB "${SOURCESDK_TIER0_IMPLIB_FILENAME}"
		)
	else()
		set_target_properties(${SOURCESDK_TIER0_NAME} PROPERTIES
			IMPORTED_LOCATION "${SOURCESDK_TIER0_LIB_FILENAME}"
		)
	endif()
endif()
