if(NOT SOURCESDK_DIR)
	message(FATAL_ERROR "SOURCESDK_DIR is empty")
endif()

set(SOURCESDK_PUBLIC_TIER0_INCLUDE_DIR "${SOURCESDK_DIR}/public/tier0")

list(APPEND SOURCESDK_INCLUDE_DIRS
	${SOURCESDK_PUBLIC_TIER0_INCLUDE_DIR}
)

append_sourcesdk_shared_library(SOURCESDK_LINK_LIBRARIES tier0)
