if(NOT PROTOBUFS_DIR)
	message(FATAL_ERROR "PROTOBUFS_DIR is empty")
endif()

set(SOURCESDK_MANIFESTS_PROTO_ABSOLUTE_DIR "${PROTOBUFS_DIR}/${SOURCESDK_MANIFESTS_GAME_PROTO_DIR}")

if(EXISTS "${SOURCESDK_MANIFESTS_PROTO_ABSOLUTE_DIR}")
	list(APPEND SOURCESDK_PROTO_DIRS ${SOURCESDK_MANIFESTS_PROTO_ABSOLUTE_DIR})
else()
	message(FATAL_ERROR "Folder \"${SOURCESDK_MANIFESTS_PROTO_DIR}\" hasn't found by \"${SOURCESDK_GAME_TARGET}\" target game")
endif()
