name: Build / macOS

on:
  push:
    branches: [ "main" ]
    paths: &paths
      - '.github/workflows/build-macos.yml'
      - 'cmake/**'
      - 'common/**'
      - 'devtools/bin/osx64/**'
      - 'entity2/**'
      - 'game/server/**'
      - 'game/shared/**'
      - 'interfaces/**'
      - 'kv3lib/**'
      - 'lib/osx64/**'
      - 'mathlib/**'
      - 'networksystem/**'
      - 'public/**'
      - 'sym/**'
      - 'tests/**'
      - 'thirdparty/**'
      - 'tier1/**'
      - 'CMakeGameManifests.json'
      - 'CMakeLists.txt'
      - 'CMakePresets.json'
  pull_request:
    branches: [ "main" ]
    paths: *paths
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  build:
    name: Clang - ${{ matrix.config }}
    runs-on: macos-latest

    strategy:
      matrix:
        config: [ Debug, RelWithDebInfo, Release ]
      fail-fast: false

    steps:
    - uses: actions/checkout@v7
      with:
        fetch-depth: 0
        fetch-tags: true

    - name: Fetch submodules
      run: git submodule update --init --depth 1 thirdparty/protobuf thirdparty/game_protobufs

    - name: Install packages
      run: brew install ninja

    - name: Set up environment variables
      run: |
        echo "LATEST_TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo none)" >> "$GITHUB_ENV"

    - name: Configure CMake
      run: cmake --preset ${{ matrix.config }} -DSOURCESDK_MALLOC_OVERRIDE=ON

    - name: Build
      run: cmake --build --preset ${{ matrix.config }} --parallel

    - name: Test
      if: matrix.config == 'Debug'
      run: ctest --preset ${{ matrix.config }}

    - name: Upload build artifact
      uses: actions/upload-artifact@v7
      with:
        name: ${{ github.event.repository.name }}-${{ env.LATEST_TAG }}-${{ runner.os }}-Clang-${{ matrix.config }}
        path: build/Darwin/${{ matrix.config }}/*.a
